In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("datos.csv")
df

,Unnamed: 0,Posición_0,Provincia,Superficie (km²)_0,Longitud de costa (km)[2]​[3]​_0,Código postal_1,Código Ministerio del Interior_1,Extranjeros totales_2,Provincia.1_2,% de extranjeros_2,...,2018_8,2019_8,2020_8,2021_8,2022_8,2023_8,TCAC 2016-23_8,Órgano de gobierno y administración_10,Sede (ciudad)_10,Comunidad autónoma_10
0,0,NaN,Albacete,NaN,NaN,2.0,AB,32.439,Ciudad Real,74.0,...,8.285.269,8.627.212,8.010.434,8.853.382,9.526.877,10.285.196,"35,86%",Diputación de Albacete,Palacio Provincial de Albacete (Albacete),Castilla-La Mancha
1,1,13,Alicante,5816,244,3.0,A,456.257,Gerona,218.0,...,36.463.569,37.807.882,34.503.374,38.470.028,41.939.432,46.472.807,"37,09%",Diputación de Alicante,Palacio Provincial de Alicante (Alicante),Comunidad Valenciana
2,2,12,Almería,8774,249,4.0,AL,168.886,Barcelona,173.0,...,15.282.092,16.003.582,14.764.342,14.861.150,16.494.994,18.250.223,"28,65%",Diputación de Almería,Edificio de la Diputación Provincial de Almerí...,Andalucía
3,3,5,Asturias,10 603,401,33.0,O,58.387,Soria,125.0,...,23.185.680,23.666.618,21.376.392,23.617.641,26.690.102,28.350.371,"30,79%",No tiene[1]​,No tiene[1]​,Principado de Asturias
4,4,NaN,Badajoz,NaN,NaN,6.0,BA,25.469,Lugo,66.0,...,12.609.609,12.838.980,11.979.224,12.729.424,13.644.123,14.927.003,"26,75%",Diputación de Badajoz,NaN,Extremadura
5,5,NaN,Baleares,NaN,NaN,7.0,PM / IB,NaN,NaN,NaN,...,33.185.968,34.350.576,26.669.106,30.512.146,37.189.162,41.502.526,"37,32%",NaN,NaN,NaN
6,6,15,Barcelona,7733,161,8.0,B,1.015.499,Almería,223.0,...,173.436.258,180.560.179,161.885.097,173.917.445,191.251.096,209.563.285,"32,20%",Diputación de Barcelona,Casa Serra (Barcelona),Cataluña
7,7,NaN,Burgos,NaN,NaN,9.0,BU,35.158,Ávila,82.0,...,10.494.196,10.628.487,9.620.320,10.224.118,10.709.841,11.303.996,"18,09%",Diputación de Burgos,NaN,Castilla y León
8,8,8,Cantabria,5325,284,39.0,S,44.242,Burgos,98.0,...,13.843.935,14.274.351,12.991.241,14.206.538,15.557.155,16.740.663,"29,93%",No tiene[4]​,No tiene[4]​,Cantabria
9,9,18,Castellón,6632,139,12.0,CS,107.330,Zaragoza,147.0,...,15.685.255,16.135.189,14.341.241,15.775.645,17.355.828,17.661.943,"24,18%",Diputación de Castellón,NaN,Comunidad Valenciana
10,10,23,Ceuta,19,26,51.0,CE,5.085,Jaén,34.0,...,1.611.648,1.659.979,1.535.718,1.634.006,1.766.735,1.862.863,"21,17%",NaN,NaN,NaN
11,11,NaN,Ciudad Real,NaN,NaN,13.0,CR,36.574,Granada,85.0,...,10.906.668,11.016.000,10.182.564,10.481.171,12.249.078,12.447.343,"20,32%",Diputación de Ciudad Real,Palacio de la Diputación Provincial de Ciudad ...,Castilla-La Mancha
12,12,NaN,"Coruña, La",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.211.854,27.819.424,25.501.350,27.529.654,31.218.140,33.477.736,"31,54%",NaN,NaN,NaN
13,13,NaN,Cuenca,NaN,NaN,16.0,CU,27.228,Valladolid,69.0,...,4.599.762,4.587.758,4.253.677,4.975.017,5.645.595,5.859.753,"36,59%",Diputación de Cuenca,NaN,Castilla-La Mancha
14,14,NaN,Cáceres,NaN,NaN,10.0,CC,16.608,Cádiz,49.0,...,8.103.645,8.327.152,7.518.119,8.822.093,9.842.522,10.265.612,"40,76%",Diputación de Cáceres,NaN,Extremadura
15,15,7,Cádiz,7436,285,11.0,CA,62.166,Teruel,127.0,...,22.462.629,23.352.580,20.477.353,22.876.782,25.860.425,26.783.989,"28,28%",Diputación de Cádiz,Palacio de la Aduana (Cádiz),Andalucía
16,16,NaN,Córdoba,NaN,NaN,14.0,CO,26.537,Orense,69.0,...,14.292.383,14.237.228,13.134.510,14.512.133,15.518.254,17.217.243,"26,90%",Diputación de Córdoba,Palacio de la Merced (Córdoba),Andalucía
17,17,Total:,España,505 944,7 661,NaN,NaN,NaN,NaN,NaN,...,1.212.276.000,1.253.710.000,1.129.214.000,1.235.474.000,1.375.863.000,1.497.761.000,"33,38%",NaN,NaN,NaN
18,18,11,Gerona,5910,260,17.0,GE / GI,178.578,Castellón,175.0,...,21.178.933,22.059.649,19.755.932,23.348.038,26.290.879,29.157.484,"40,39%",Diputación de Gerona,NaN,Cataluña
19,19,22,Granada,12 531,79,18.0,GR,79.669,Melilla,136.0,...,16.798.633,17.538.085,15.967.883,17.357.256,19.181.269,20.836.996,"31,15%",Diputación de Granada,NaN,Andalucía
20,20,NaN,Guadalajara,NaN,NaN,19.0,GU,43.993,Guipúzcoa,96.0,...,5.379.941,5.647.861,5.225.237,5.804.558,6.782.836,6.878.584,"44,79%",Diputación de Guadalajara,Palacio de la Diputación de Guadalajara (Guada...,Castilla-La Mancha
21,21,21,Guipúzcoa,1909,92,20.0,SS,70.347,Segovia,127.0,...,23.594.075,24.464.797,21.891.774,24.644.193,26.370.267,28.427.601,"32,42%",Diputación Foral de Guipúzcoa,NaN,País Vasco
22,22,20,Huelva,10 148,122,21.0,H,56.526,Toledo,124.0,...,10.616.525,10.650.577,9.353.422,10.640.222,12.859.210,13.183.665,"41,93%",Diputación de Huelva,NaN,Andalucía
23,23,NaN,Huesca,NaN,NaN,22.0,HU,33.393,Cantabria,75.0,...,6.339.722,6.567.333,6.331.038,6.780.105,7.631.866,8.167.881,"31,23%",Diputación de Huesca,NaN,Aragón
24,24,1,Islas Baleares,4992,1 283,NaN,NaN,254.624,Málaga,182.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No tiene[3]​,No tiene[3]​,Islas Baleares
25,25,NaN,Jaén,NaN,NaN,23.0,J,21.416,Salamanca,61.0,...,11.635.259,11.267.290,10.781.405,11.853.935,11.738.138,13.052.058,"19,70%",Diputación de Jaén,Palacio Provincial (Jaén),Andalucía
26,26,2,La Coruña,7950,956,15.0,C,60.256,Navarra,125.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diputación de La Coruña,NaN,Galicia
27,27,NaN,La Rioja,NaN,NaN,26.0,LO,46.625,Huelva,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No tiene[5]​,No tiene[5]​,La Rioja
28,28,3,Las Palmas,4066,799,35.0,GC,157.102,Guadalajara,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No tiene[6]​,No tiene[6]​,Canarias
29,29,NaN,León,NaN,NaN,24.0,LE,24.291,Ceuta,63.0,...,9.777.598,10.041.788,9.276.493,10.454.424,11.757.261,12.193.704,"32,08%",Diputación de León,Palacio de los Guzmanes (León),Castilla y León
30,30,17,Lugo,9856,144,27.0,LU,21.142,Palencia,58.0,...,7.768.980,7.822.876,6.945.138,7.637.441,8.568.467,9.406.547,"25,88%",Diputación de Lugo,NaN,Galicia
31,31,NaN,Lérida,NaN,NaN,25.0,L,91.408,Valencia,144.0,...,12.191.707,12.766.171,11.635.303,12.954.308,13.789.781,15.081.546,"24,02%",Diputación de Lérida,Palacio de la Diputación de Lérida (Lérida),Cataluña
32,32,NaN,Madrid,NaN,NaN,28.0,M,1.072.173,Alicante,230.0,...,233.735.808,243.889.359,221.061.932,239.837.609,267.171.570,295.939.562,"37,99%",No tiene[7]​,No tiene[7]​,Comunidad de Madrid
33,33,24,Melilla,13,12,52.0,ML,11.260,Sevilla,48.0,...,1.510.904,1.560.101,1.452.031,1.534.391,1.655.971,1.753.666,"20,71%",NaN,NaN,NaN
34,34,10,Murcia,11 313,274,30.0,MU,242.578,Tarragona,182.0,...,31.715.345,33.000.651,30.440.306,33.603.543,37.380.806,39.838.741,"32,76%",No tiene[8]​,No tiene[8]​,Región de Murcia
35,35,14,Málaga,7308,175,29.0,MA,320.766,Lérida,200.0,...,31.204.388,32.530.116,28.516.619,32.619.883,37.226.438,41.235.144,"44,62%",Diputación de Málaga,NaN,Andalucía
36,36,NaN,Navarra,NaN,NaN,31.0,NaN,84.896,Cuenca,136.0,...,20.235.995,21.070.268,19.160.726,20.821.017,23.204.474,24.975.376,"32,07%",No tiene[9]​,No tiene[9]​,Comunidad Foral de Navarra
37,37,NaN,Orense,NaN,NaN,32.0,OR / OU,20.924,León,54.0,...,6.785.155,7.138.919,6.420.384,7.262.638,8.128.954,8.914.517,"41,11%",Diputación de Orense,NaN,Galicia
38,38,25,Otras (Chafarinas y Vélez de la Gomera),—,9,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,39,NaN,Palencia,NaN,NaN,34.0,P,9.356,Badajoz,38.0,...,4.375.118,4.417.915,4.042.436,4.326.851,4.713.440,5.047.540,"20,99%",Diputación de Palencia,Palacio de la Diputación de Palencia (Palencia),Castilla y León
40,40,NaN,"Palmas, Las",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.974.312,23.478.690,19.159.502,21.364.107,25.483.866,28.124.631,"33,08%",NaN,NaN,NaN
41,41,6,Pontevedra,4495,398,36.0,PO,47.105,Álava,109.0,...,20.883.374,21.720.786,20.140.306,21.957.653,23.720.820,25.662.611,"32,81%",Diputación de Pontevedra,Palacio de la Diputación de Pontevedra (Pontev...,Galicia
42,42,NaN,"Rioja, La",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.649.852,8.889.997,8.186.915,8.735.750,9.767.469,10.476.650,"29,76%",NaN,NaN,NaN
43,43,NaN,Salamanca,NaN,NaN,37.0,SA,20.516,La Coruña,54.0,...,6.894.146,7.149.679,6.583.497,7.386.843,8.647.606,9.604.292,"47,50%",Diputación de Salamanca,Palacio de La Salina (Salamanca),Castilla y León
44,44,4,Santa Cruz de Tenerife,3381,702,38.0,TF,161.983,Murcia,158.0,...,21.634.954,22.288.142,18.427.897,20.043.168,23.424.330,25.865.458,"30,33%",No tiene[10]​,No tiene[10]​,Canarias
45,45,NaN,Segovia,NaN,NaN,40.0,SG,21.309,Asturias,59.0,...,3.377.956,3.482.508,3.163.709,3.646.707,4.049.897,4.408.019,"30,50%",Diputación de Segovia,NaN,Castilla y León
46,46,NaN,Sevilla,NaN,NaN,41.0,SE,94.994,La Rioja,144.0,...,39.602.392,40.899.272,37.457.375,41.574.995,45.485.662,48.846.749,"33,19%",Diputación de Sevilla,NaN,Andalucía
47,47,NaN,Soria,NaN,NaN,42.0,SO,10.936,Cáceres,43.0,...,2.492.230,2.530.167,2.291.715,2.555.836,2.709.532,2.825.443,"30,59%",Diputación de Soria,NaN,Castilla y León
48,48,9,Tarragona,6303,278,43.0,T,155.717,Madrid,154.0,...,24.294.389,24.779.819,21.581.103,24.600.611,27.455.651,29.471.710,"27,82%",Diputación de Tarragona,NaN,Cataluña
49,49,NaN,Teruel,NaN,NaN,44.0,TE,17.169,Pontevedra,50.0,...,3.381.320,3.422.528,3.120.527,3.529.024,4.072.915,4.324.273,"32,80%",Diputación de Teruel,NaN,Aragón
50,50,NaN,Toledo,NaN,NaN,45.0,TO,90.060,Las Palmas,137.0,...,13.119.285,13.514.472,12.582.448,14.009.858,15.827.632,17.074.065,"40,19%",Diputación de Toledo,Edificio de la Diputación de Toledo (Toledo),Castilla-La Mancha
51,51,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,52,19,Valencia,10 763,135,46.0,V,388.076,Islas Baleares,208.0,...,60.600.750,62.645.457,57.222.556,62.141.233,68.288.134,75.521.155,"34,66%",Diputación de Valencia,Palacio de la Baylía (Valencia),Comunidad Valenciana
53,53,NaN,Valladolid,NaN,NaN,47.0,VA,36.139,Albacete,84.0,...,14.353.734,14.611.199,13.556.027,13.949.687,15.264.558,16.425.196,"25,18%",Diputación de Valladolid,Palacio de Pimentel (Valladolid),Castilla y León
54,54,16,Vizcaya,2217,154,48.0,BI,105.893,Huesca,146.0,...,35.599.877,36.737.656,33.016.596,35.910.195,41.009.633,44.229.902,"31,30%",Diputación Foral de Vizcaya,Palacio de la Diputación Foral de Vizcaya (Bil...,País Vasco
55,55,NaN,Zamora,NaN,NaN,49.0,ZA,8.199,Córdoba,35.0,...,3.369.888,3.490.956,3.204.009,3.673.777,4.146.391,4.359.052,"25,36%",Diputación de Zamora,Hospital de la Encarnación (Zamora),Castilla y León
56,56,NaN,Zaragoza,NaN,NaN,50.0,Z,146.263,Santa Cruz de Tenerife,151.0,...,27.492.854,28.475.192,26.504.006,28.473.028,31.964.054,34.285.966,"36,81%",Diputación de Zaragoza,Palacio de la Diputación Provincial (Zaragoza),Aragón
57,57,NaN,Álava,NaN,NaN,1.0,VI,36.831,Vizcaya,91.0,...,12.721.159,12.797.528,11.764.228,11.958.641,12.838.267,14.090.604,"17,81%",Diputación Foral de Álava,Palacio de la Diputación Foral de Álava (Vitoria),País Vasco
58,58,NaN,Ávila,NaN,NaN,5.0,AV,13.085,Zamora,49.0,...,3.191.993,3.296.499,3.056.383,3.247.657,3.468.682,3.726.678,"24,08%",Diputación de Ávila,Torreón de los Guzmanes[2]​ (Ávila),Castilla y León

In [7]:
import pandas as pd
import numpy as np 
df = pd.read_csv("datos.csv", index_col=0)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# eliminar filas que no interesan
filas_basura = ["España", "Total", "Otras (Chafarinas y Vélez de la Gomera)"]
df = df[~df["Provincia"].isin(filas_basura)]

# normalizar nombres de provincias


# detectar columnas duplicadas


# convertir números que están como texto

def limpiar_numero(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = x.replace(" ", "")
    x = x.replace(".", "")
    x = x.replace(",", ".")
    x = x.replace("%", "")
    x = x.replace("—", "")
    x = x.replace("-", "")
    return pd.to_numeric(x, errors="coerce")

cols_numericas = ["Población_5", "Presupuesto (€)_5", "Densidad (hab./km²)_5", "2023_8", "TCAC 2016-23_8"]

for col in cols_numericas:
    df[col] = df[col].apply(limpiar_numero)


# unificar columnas
def unificar_columnas(df, nombre_base):
    cols = [c for c in df.columns if c == nombre_base or c.startswith(nombre_base + "_")]
    if not cols:
        return df
    
    df[nombre_base] = df[cols].bfill(axis=1).iloc[:, 0]
    cols_a_borrar = [c for c in cols if c != nombre_base]
    df = df.drop(columns=cols_a_borrar, errors="ignore")
    return df

df = unificar_columnas(df, "Comunidad autónoma")
df = unificar_columnas(df, "Capital")
df = unificar_columnas(df, "Población")
df = unificar_columnas(df, "Provincia")

# partir la tabla de extranjeros en dos


df

,Posición_0,Provincia,Superficie (km²)_0,Longitud de costa (km)[2]​[3]​_0,Código postal_1,Código Ministerio del Interior_1,Extranjeros totales_2,Provincia.1_2,% de extranjeros_2,Puesto_5,Escudo_5,Presupuesto (€)_5,Porcentaje población_5,Densidad (hab./km²)_5,Superficie (km²)[2]​_5,Porcentaje superficie_5,Mapa_5,Ciudad más poblada*_5,Posición_8,2016_8,2017_8,2018_8,2019_8,2020_8,2021_8,2022_8,2023_8,TCAC 2016-23_8,Órgano de gobierno y administración_10,Sede (ciudad)_10,Comunidad autónoma,Capital,Población
0,NaN,Albacete,NaN,NaN,2.0,AB,32.439,Ciudad Real,74.0,34,NaN,NaN,0.8 %,2618.0,14 924,2.95 %,NaN,Albacete,37,7.570.409,7.992.903,8.285.269,8.627.212,8.010.434,8.853.382,9.526.877,10285196.0,35.86,Diputación de Albacete,Palacio Provincial de Albacete (Albacete),Castilla-La Mancha,Albacete,NaN
1,13,Alicante,5816,244,3.0,A,456.257,Gerona,218.0,4,NaN,NaN,4.14 %,34959.0,5817,1.15 %,NaN,Alicante,5,33.899.084,35.422.930,36.463.569,37.807.882,34.503.374,38.470.028,41.939.432,46472807.0,37.09,Diputación de Alicante,Palacio Provincial de Alicante (Alicante),Comunidad Valenciana,Alicante,NaN
2,12,Almería,8774,249,4.0,AL,168.886,Barcelona,173.0,21,NaN,NaN,1.57 %,8781.0,8775,1.73 %,NaN,Almería,22,14.185.706,15.159.388,15.282.092,16.003.582,14.764.342,14.861.150,16.494.994,18250223.0,28.65,Diputación de Almería,Edificio de la Diputación Provincial de Almerí...,Andalucía,Almería,NaN
3,5,Asturias,10 603,401,33.0,O,58.387,Soria,125.0,14,NaN,NaN,2.07 %,9573.0,10 604,2.1 %,NaN,Gijón,15,21.675.441,22.538.267,23.185.680,23.666.618,21.376.392,23.617.641,26.690.102,28350371.0,30.79,No tiene[1]​,No tiene[1]​,Asturias,Oviedo,NaN
4,NaN,Badajoz,NaN,NaN,6.0,BA,25.469,Lugo,66.0,25,NaN,NaN,1.35 %,3056.0,21 766,4.3 %,NaN,Badajoz,29,11.776.505,12.419.839,12.609.609,12.838.980,11.979.224,12.729.424,13.644.123,14927003.0,26.75,Diputación de Badajoz,NaN,Extremadura,Badajoz,NaN
5,NaN,Baleares,NaN,NaN,7.0,PM / IB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,30.223.284,31.746.251,33.185.968,34.350.576,26.669.106,30.512.146,37.189.162,41502526.0,37.32,NaN,NaN,NaN,NaN,NaN
6,15,Barcelona,7733,161,8.0,B,1.015.499,Almería,223.0,2,NaN,NaN,12.13 %,77121.0,7728,1.53 %,NaN,Barcelona,2,158.516.150,166.618.005,173.436.258,180.560.179,161.885.097,173.917.445,191.251.096,209563285.0,32.20,Diputación de Barcelona,Casa Serra (Barcelona),Cataluña,Barcelona,NaN
7,NaN,Burgos,NaN,NaN,9.0,BU,35.158,Ávila,82.0,36,NaN,NaN,0.74 %,2538.0,14 292,2.82 %,NaN,Burgos,35,9.572.090,10.054.308,10.494.196,10.628.487,9.620.320,10.224.118,10.709.841,11303996.0,18.09,Diputación de Burgos,NaN,Castilla y León,Burgos,NaN
8,8,Cantabria,5325,284,39.0,S,44.242,Burgos,98.0,28,NaN,NaN,1.21 %,11156.0,5321,1.05 %,NaN,Santander,26,12.833.899,13.318.023,13.843.935,14.274.351,12.991.241,14.206.538,15.557.155,16740663.0,29.93,No tiene[4]​,No tiene[4]​,Cantabria,Santander,NaN
9,18,Castellón,6632,139,12.0,CS,107.330,Zaragoza,147.0,26,NaN,NaN,1.28 %,9421.0,6636,1.32%,NaN,Castellón de la Plana,23,14.223.009,15.506.038,15.685.255,16.135.189,14.341.241,15.775.645,17.355.828,17661943.0,24.18,Diputación de Castellón,NaN,Comunidad Valenciana,Castellón de la Plana,NaN
10,23,Ceuta,19,26,51.0,CE,5.085,Jaén,34.0,52,NaN,NaN,0.17 %,417835.0,19,0.004 %,NaN,-,51,1.537.398,1.553.567,1.611.648,1.659.979,1.535.718,1.634.006,1.766.735,1862863.0,21.17,NaN,NaN,Ceuta,-,NaN
11,NaN,Ciudad Real,NaN,NaN,13.0,CR,36.574,Granada,85.0,31,NaN,NaN,1.01 %,2498.0,19 813,3.92 %,NaN,Ciudad Real,33,10.345.475,10.690.171,10.906.668,11.016.000,10.182.564,10.481.171,12.249.078,12447343.0,20.32,Diputación de Ciudad Real,Palacio de la Diputación Provincial de Ciudad ...,Castilla-La Mancha,Ciudad Real,NaN
12,NaN,"Coruña, La",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,25.451.524,26.097.818,27.211.854,27.819.424,25.501.350,27.529.654,31.218.140,33477736.0,31.54,NaN,NaN,NaN,NaN,NaN
13,NaN,Cuenca,NaN,NaN,16.0,CU,27.228,Valladolid,69.0,44,NaN,NaN,0.41 %,1166.0,17 140,3.39 %,NaN,Cuenca,44,4.290.139,4.421.111,4.599.762,4.587.758,4.253.677,4.975.017,5.645.595,5859753.0,36.59,Diputación de Cuenca,NaN,Castilla-La Mancha,Cuenca,NaN
14,NaN,Cáceres,NaN,NaN,10.0,CC,16.608,Cádiz,49.0,35,NaN,NaN,0.79 %,1954.0,19 868,3.93 %,NaN,Cáceres,38,7.292.966,7.749.707,8.103.645,8.327.152,7.518.119,8.822.093,9.842.522,10265612.0,40.76,Diputación de Cáceres,NaN,Extremadura,Cáceres,NaN
15,7,Cádiz,7436,285,11.0,CA,62.166,Teruel,127.0,8,NaN,NaN,2.57 %,16955.0,7440,1.47 %,NaN,Jerez de la Frontera,17,20.879.560,21.860.392,22.462.629,23.352.580,20.477.353,22.876.782,25.860.425,26783989.0,28.28,Diputación de Cádiz,Palacio de la Aduana (Cádiz),Andalucía,Cádiz,NaN
16,NaN,Córdoba,NaN,NaN,14.0,CO,26.537,Orense,69.0,20,NaN,NaN,1.57 %,5614.0,13 771,2.72 %,NaN,Córdoba,24,13.567.313,14.113.022,14.292.383,14.237.228,13.134.510,14.512.133,15.518.254,17217243.0,26.90,Diputación de Córdoba,Palacio de la Merced (Córdoba),Andalucía,Córdoba,NaN
18,11,Gerona,5910,260,17.0,GE / GI,178.578,Castellón,175.0,19,NaN,NaN,1.69 %,14051.0,5910,1.17 %,NaN,Gerona,13,20.769.493,20.612.222,21.178.933,22.059.649,19.755.932,23.348.038,26.290.879,29157484.0,40.39,Diputación de Gerona,NaN,Cataluña,Gerona,NaN
19,22,Granada,12 531,79,18.0,GR,79.669,Melilla,136.0,17,NaN,NaN,1.93 %,7478.0,12 647,2.5 %,NaN,Granada,21,15.888.251,16.314.359,16.798.633,17.538.085,15.967.883,17.357.256,19.181.269,20836996.0,31.15,Diputación de Granada,NaN,Andalucía,Granada,NaN
20,NaN,Guadalajara,NaN,NaN,19.0,GU,43.993,Guipúzcoa,96.0,42,NaN,NaN,0.58 %,234.0,12 214,2.41 %,NaN,Guadalajara,43,4.750.576,5.106.037,5.379.941,5.647.861,5.225.237,5.804.558,6.782.836,6878584.0,44.79,Diputación de Guadalajara,Palacio de la Diputación de Guadalajara (Guada...,Castilla-La Mancha,Guadalajara,NaN
21,21,Guipúzcoa,1909,92,20.0,SS,70.347,Segovia,127.0,23,NaN,NaN,1.49 %,37028.0,1980,0.39 %,NaN,San Sebastián,14,21.467.926,22.934.894,23.594.075,24.464.797,21.891.774,24.644.193,26.370.267,28427601.0,32.42,Diputación Foral de Guipúzcoa,NaN,País Vasco,San Sebastián,NaN
22,20,Huelva,10 148,122,21.0,H,56.526,Toledo,124.0,29,NaN,NaN,1.1 %,532.0,10 128,2 %,NaN,Huelva,31,9.288.980,10.037.865,10.616.525,10.650.577,9.353.422,10.640.222,12.859.210,13183665.0,41.93,Diputación de Huelva,NaN,Andalucía,Huelva,NaN
23,NaN,Huesca,NaN,NaN,22.0,HU,33.393,Cantabria,75.0,43,NaN,NaN,0.47 %,1472.0,15 636,3.09 %,NaN,Huesca,42,6.224.092,6.275.164,6.339.722,6.567.333,6.331.038,6.780.105,7.631.866,8167881.0,31.23,Diputación de Huesca,NaN,Aragón,Huesca,NaN
24,1,Islas Baleares,4992,1 283,NaN,NaN,254.624,Málaga,182.0,9,NaN,NaN,2.54 %,25037.0,4992,0.99 %,NaN,Palma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No tiene[3]​,No tiene[3]​,Islas Baleares,Palma,NaN
25,NaN,Jaén,NaN,NaN,23.0,J,21.416,Salamanca,61.0,27,NaN,NaN,1.26 %,458.0,13 496,2.67 %,NaN,Jaén,32,10.903.626,11.122.181,11.635.259,11.267.290,10.781.405,11.853.935,11.738.138,13052058.0,19.70,Diputación de Jaén,Palacio Provincial (Jaén),Andalucía,Jaén,NaN
26,2,La Coruña,7950,956,15.0,C,60.256,Navarra,125.0,12,NaN,NaN,2.31 %,14283.0,7950,1.57 %,NaN,La Coruña,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diputación de La Coruña,NaN,Galicia,La Coruña,NaN
27,NaN,La Rioja,NaN,NaN,26.0,LO,46.625,Huelva,106.0,39,NaN,NaN,0.67 %,6478.0,5045,1 %,NaN,Logroño,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No tiene[5]​,No tiene[5]​,La Rioja,Logroño,NaN
28,3,Las Palmas,4066,799,35.0,GC,157.102,Guadalajara,155.0,10,NaN,NaN,2.38 %,28813.0,4066,0.8 %,NaN,Las Palmas de Gran Canaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No tiene[6]​,No tiene[6]​,Canarias,Las Palmas de Gran Canaria,NaN
29,NaN,León,NaN,NaN,24.0,LE,24.291,Ceuta,63.0,33,NaN,NaN,0.91 %,2875.0,15 581,3.08 %,NaN,León,34,9.231.953,9.506.147,9.777.598,10.041.788,9.276.493,10.454.424,11.757.261,12193704.0,32.08,Diputación de León,Palacio de los Guzmanes (León),Castilla y León,León,NaN
30,17,Lugo,9856,144,27.0,LU,21.142,Palencia,58.0,40,NaN,NaN,0.66 %,3308.0,9856,1.95 %,NaN,Lugo,40,7.472.883,7.458.900,7.768.980,7.822.876,6.945.138,7.637.441,8.568.467,9406547.0,25.88,Diputación de Lugo,NaN,Galicia,Lugo,NaN
31,NaN,Lérida,NaN,NaN,25.0,L,91.408,Valencia,144.0,32,NaN,NaN,0.93 %,3765.0,12 172,2.41 %,NaN,Lérida,28,12.160.547,11.803.319,12.191.707,12.766.171,11.635.303,12.954.308,13.789.781,15081546.0,24.02,Diputación de Lérida,Palacio de la Diputación de Lérida (Lérida),Cataluña,Lérida,NaN
32,NaN,Madrid,NaN,NaN,28.0,M,1.072.173,Alicante,230.0,1,NaN,NaN,14.48 %,88613.0,8028,1.59 %,NaN,Madrid,1,214.469.101,224.373.156,233.735.808,243.889.359,221.061.932,239.837.609,267.171.570,295939562.0,37.99,No tiene[7]​,No tiene[7]​,Comunidad de Madrid,Madrid,NaN
33,24,Melilla,13,12,52.0,ML,11.260,Sevilla,48.0,51,NaN,NaN,0.18 %,725558.0,13,0.003 %,NaN,-,52,1.452.752,1.466.610,1.510.904,1.560.101,1.452.031,1.534.391,1.655.971,1753666.0,20.71,NaN,NaN,Melilla,-,NaN
34,10,Murcia,11 313,274,30.0,MU,242.578,Tarragona,182.0,7,NaN,NaN,3.23 %,14027.0,11 314,2.24 %,NaN,Murcia,9,30.009.138,31.192.490,31.715.345,33.000.651,30.440.306,33.603.543,37.380.806,39838741.0,32.76,No tiene[8]​,No tiene[8]​,Región de Murcia,Murcia,NaN
35,14,Málaga,7308,175,29.0,MA,320.766,Lérida,200.0,6,NaN,NaN,3.65 %,24517.0,7306,1.44 %,NaN,Málaga,8,28.513.572,29.891.621,31.204.388,32.530.116,28.516.619,32.619.883,37.226.438,41235144.0,44.62,Diputación de Málaga,NaN,Andalucía,Málaga,NaN
36,NaN,Navarra,NaN,NaN,31.0,NaN,84.896,Cuenca,136.0,24,NaN,NaN,1.39 %,6581.0,10 391,2.05 %,NaN,Pamplona,20,18.911.331,19.698.794,20.235.995,21.070.268,19.160.726,20.821.017,23.204.474,24975376.0,32.07,No tiene[9]​,No tiene[9]​,Navarra,Pamplona,NaN
37,NaN,Orense,NaN,NaN,32.0,OR / OU,20.924,León,54.0,41,NaN,NaN,0.62 %,4197.0,7273,1.44 %,NaN,Orense,41,6.317.422,6.517.804,6.785.155,7.138.919,6.420.384,7.262.638,8.128.954,8914517.0,41.11,Diputación de Orense,NaN,Galicia,Orense,NaN
39,NaN,Palencia,NaN,NaN,34.0,P,9.356,Badajoz,38.0,47,NaN,NaN,0.32 %,1971.0,8052,1.59 %,NaN,Palencia,45,4.171.878,4.070.286,4.375.118,4.417.915,4.042.436,4.326.851,4.713.440,5047540.0,20.99,Diputación de Palencia,Palacio de la Diputación de Palencia (Palencia),Castilla y León,Palencia,NaN
40,NaN,"Palmas, Las",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,21.133.454,22.089.679,22.974.312,23.478.690,19.159.502,21.364.107,25.483.866,28124631.0,33.08,NaN,NaN,NaN,NaN,NaN
41,6,Pontevedra,4495,398,36.0,PO,47.105,Álava,109.0,16,NaN,NaN,1.93 %,21086.0,4495,0.89 %,NaN,Vigo,19,19.322.194,20.556.330,20.883.374,21.720.786,20.140.306,21.957.653,23.720.820,25662611.0,32.81,Diputación de Pontevedra,Palacio de la Diputación de Pontevedra (Pontev...,Galicia,Pontevedra,NaN
42,NaN,"Rioja, La",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,8.074.094,8.351.707,8.649.852,8.889.997,8.186.915,8.735.750,9.767.469,10476650.0,29.76,NaN,NaN,NaN,NaN,NaN
43,NaN,Salamanca,NaN,NaN,37.0,SA,20.516,La Coruña,54.0,38,NaN,NaN,0.67 %,2659.0,12 350,2.44 %,NaN,Salamanca,39,6.511.439,6.692.406,6.894.146,7.149.679,6.583.497,7.386.843,8.647.606,9604292.0,47.50,Diputación de Salamanca,Palacio de La Salina (Salamanca),Castilla y León,Salamanca,NaN
44,4,Santa Cruz de Tenerife,3381,702,38.0,TF,161.983,Murcia,158.0,13,NaN,NaN,2.21 %,3216.0,3381,0.67 %,NaN,Santa Cruz de Tenerife,18,19.846.216,20.946.160,21.634.954,22.288.142,18.427.897,20.043.168,23.424.330,25865458.0,30.33,No tiene[10]​,No tiene[10]​,Canarias,Santa Cruz de Tenerife,NaN
45,NaN,Segovia,NaN,NaN,40.0,SG,21.309,Asturias,59.0,48,NaN,NaN,0.32 %,2287.0,6921,1.37 %,NaN,Segovia,46,3.377.877,3.260.124,3.377.956,3.482.508,3.163.709,3.646.707,4.049.897,4408019.0,30.50,Diputación de Segovia,NaN,Castilla y León,Segovia,NaN
46,NaN,Sevilla,NaN,NaN,41.0,SE,94.994,La Rioja,144.0,5,NaN,NaN,4.03 %,1409.0,14 036,2.77 %,NaN,Sevilla,4,36.674.889,38.290.656,39.602.392,40.899.272,37.457.375,41.574.995,45.485.662,48846749.0,33.19,Diputación de Sevilla,NaN,Andalucía,Sevilla,NaN
47,NaN,Soria,NaN,NaN,42.0,SO,10.936,Cáceres,43.0,50,NaN,NaN,0.18 %,875.0,10 306,2.04 %,NaN,Soria,50,2.163.618,2.209.607,2.492.230,2.530.167,2.291.715,2.555.836,2.709.532,2825443.0,30.59,Diputación de Soria,NaN,Castilla y León,Soria,NaN
48,9,Tarragona,6303,278,43.0,T,155.717,Madrid,154.0,18,NaN,NaN,1.78 %,13891.0,6303,1.25 %,NaN,Tarragona,12,23.056.357,24.106.231,24.294.389,24.779.819,21.581.103,24.600.611,27.455.651,29471710.0,27.82,Diputación de Tarragona,NaN,Cataluña,Tarragona,NaN
49,NaN,Teruel,NaN,NaN,44.0,TE,17.169,Pontevedra,50.0,49,NaN,NaN,0.28 %,919.0,14 810,2.93 %,NaN,Teruel,48,3.256.277,3.222.753,3.381.320,3.422.528,3.120.527,3.529.024,4.072.915,4324273.0,32.80,Diputación de Teruel,NaN,Aragón,Teruel,NaN
50,NaN,Toledo,NaN,NaN,45.0,TO,90.060,Las Palmas,137.0,22,NaN,NaN,1.54 %,4913.0,15 370,3.04 %,NaN,Toledo,25,12.179.643,12.558.737,13.119.285,13.514.472,12.582.448,14.009.858,15.827.632,17074065.0,40.19,Diputación de Toledo,Edificio de la Diputación de Toledo (Toledo),Castilla-La Mancha,Toledo,NaN
52,19,Valencia,10 763,135,46.0,V,388.076,Islas Baleares,208.0,3,NaN,NaN,5.63 %,2565.0,10 807,2.14 %,NaN,Valencia,3,56.083.303,57.737.744,60.600.750,62.645.457,57.222.556,62.141.233,68.288.134,75521155.0,34.66,Diputación de Valencia,Palacio de la Baylía (Valencia),Comunidad Valenciana,Valencia,NaN
53,NaN,Valladolid,NaN,NaN,47.0,VA,36.139,Albacete,84.0,30,NaN,NaN,1.08 %,6518.0,8110,1.6 %,NaN,Valladolid,27,13.121.197,13.737.381,14.353.734,14.611.199,13.556.027,13.949.687,15.264.558,16425196.0,25.18,Diputación de Valladolid,Palacio de Pimentel (Valladolid),Castilla y León,Valladolid,NaN
54,16,Vizcaya,2217,154,48.0,BI,105.893,Huesca,146.0,11,NaN,NaN,2.38 %,52649.0,2217,0.44 %,NaN,Bilbao,6,33.686.330,34.314.272,35.599.877,36.737.656,33.016.596,35.910.195,41.009.633,44229902.0,31.30,Diputación Foral de Vizcaya,Palacio de la Diputación Foral de Vizcaya (Bil...,País Vasco,Bilbao,NaN
55,NaN,Zamora,NaN,NaN,49.0,ZA,8.199,Córdoba,35.0,45,NaN,NaN,0.34 %,1568.0,10 561,2.09 %,NaN,Zamora,47,3.477.147,3.261.080,3.369.888,3.490.956,3.204.009,3.673.777,4.146.391,4359052.0,25.36,Diputación de Zamora,Hospital de la Encarnación (Zamora),Castilla y León,Zamora,NaN
56,NaN,Zaragoza,NaN,NaN,50.0,Z,146.263,Santa Cruz de Tenerife,151.0,15,NaN,NaN,2.03 %,578.0,17 274,3.41 %,NaN,Zaragoza,10,25.061.759,26.485.627,27.492.854,28.475.192,26.504.006,28.473.028,31.964.054,34285966.0,36.81,Diputación de Zaragoza,Palacio de la Diputación Provincial (Zaragoza),Aragón,Zaragoza,NaN
57,NaN,Álava,NaN,NaN,1.0,VI,36.831,Vizcaya,91.0,37,NaN,NaN,0.7 %,1126.0,3037,0.6 %,NaN,Vitoria,30,11.960.737,12.336.129,12.721.159,12.797.528,11.764.228,11.958.641,12.838.267,14090604.0,17.81,Diputación Foral de Álava,Palacio de la Diputación Foral de Álava (Vitoria),País Vasco,Vitoria,NaN
58,NaN,Ávila,NaN,NaN,5.0,AV,13.085,Zamora,49.0,46,NaN,NaN,0.33 %,1997.0,8050,1.59 %,NaN,Ávila,49,3.003.333,3.087.954,3.191.993,3.296.499,3.056.383,3.247.657,3.468.682,3726678.0,24.08,Diputación de Ávila,Torreón de los Guzmanes[2]​ (Ávila),Castilla y León,Ávila,NaN

In [5]:
print(df.columns.tolist())

['Posición_0', 'Provincia', 'Superficie (km²)_0', 'Longitud de costa (km)[2]\u200b[3]\u200b_0', 'Código postal_1', 'Código Ministerio del Interior_1', 'Extranjeros totales_2', 'Provincia.1_2', '% de extranjeros_2', 'Puesto_5', 'Escudo_5', 'Población_5', 'Presupuesto (€)_5', 'Porcentaje población_5', 'Densidad (hab./km²)_5', 'Superficie (km²)[2]\u200b_5', 'Porcentaje superficie_5', 'Mapa_5', 'Capital_5', 'Ciudad más poblada*_5', 'Comunidad autónoma_5', 'Posición_8', '2016_8', '2017_8', '2018_8', '2019_8', '2020_8', '2021_8', '2022_8', '2023_8', 'TCAC 2016-23_8', 'Órgano de gobierno y administración_10', 'Sede (ciudad)_10', 'Comunidad autónoma_10']

In [1]:
! pip install numpy

Requirement already satisfied: numpy in c:\users\carlo\meteora-lp-bot\.venv\lib\site-packages (2.2.6)

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv("datos_2.csv")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)


def normalizar_provincia(x):
    if pd.isna(x):
        return x

    x = str(x).strip()

    equivalencias = {
        "Coruña, La": "La Coruña",
        "Palmas, Las": "Las Palmas",
        "Rioja, La": "La Rioja",
        "Baleares": "Islas Baleares",
        "Gerona": "Girona",
        "Lérida": "Lleida",
        "Orense": "Ourense",
        "Álava": "Araba/Álava",
        "Guipúzcoa": "Gipuzkoa",
        "Vizcaya": "Bizkaia"
    }

    return equivalencias.get(x, x)


# 1. eliminar filas que no interesan
filas_basura = ["España", "Total", "Otras (Chafarinas y Vélez de la Gomera)", "-", "nan"]
df = df[~df["Provincia"].astype(str).isin(filas_basura)].copy()

# 2. normalizar nombres de provincias
df["Provincia"] = df["Provincia"].astype(str).str.strip().apply(normalizar_provincia)


# 3. función para unificar columnas repetidas
def unificar_columnas(df, nombre_base):
    cols = [c for c in df.columns if c == nombre_base or c.startswith(nombre_base + "_")]
    if not cols:
        return df

    df[nombre_base] = df[cols].bfill(axis=1).iloc[:, 0]
    cols_a_borrar = [c for c in cols if c != nombre_base]
    df = df.drop(columns=cols_a_borrar, errors="ignore")
    return df


# 4. unificar columnas equivalentes
bases_a_unificar = [
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Población",
    "Presupuesto (€)",
    "Densidad (hab./km²)",
    "Superficie (km²)",
    "Código postal",
    "Código Ministerio del Interior",
    "Órgano de gobierno y administración",
    "Sede (ciudad)",
    "Extranjeros totales",
    "% de extranjeros",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23"
]

for base in bases_a_unificar:
    df = unificar_columnas(df, base)


# 5. consolidar filas duplicadas por provincia
def first_non_null(series):
    s = series.dropna()
    return s.iloc[0] if not s.empty else np.nan

df = df.groupby("Provincia", as_index=False).agg(first_non_null)


# 6. limpieza numérica
def limpiar_numero(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip()

    # nulos y símbolos raros
    if x in ["-", "—", "", "nan", "None"]:
        return np.nan

    # quitar referencias tipo [2], [3], etc.
    import re
    x = re.sub(r"\[\d+\]", "", x)

    # quitar espacios
    x = x.replace(" ", "")

    # quitar %
    x = x.replace("%", "")

    # formato español:
    # 1.234.567,89 -> 1234567.89
    # 390 751 -> 390751
    x = x.replace(".", "")
    x = x.replace(",", ".")

    return pd.to_numeric(x, errors="coerce")


# 7. columnas numéricas a convertir
cols_numericas = [
    "Extranjeros totales",
    "% de extranjeros",
    "Población",
    "Presupuesto (€)",
    "Densidad (hab./km²)",
    "Superficie (km²)",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23"
]

for col in cols_numericas:
    if col in df.columns:
        df[col] = df[col].apply(limpiar_numero)


# 8. ver columnas finales
print(df.columns.tolist())

# 9. guardar limpio
df.to_csv("datos_limpios.csv", index=False)

df

['Provincia', 'Provincia.1_3', 'Posición_4', 'Longitud de costa (km)[2]\u200b[3]\u200b_4', 'Puesto_7', 'Escudo_7', 'Porcentaje población_7', 'Superficie (km²)[2]\u200b_7', 'Porcentaje superficie_7', 'Mapa_7', 'Posición_8', 'Comunidad autónoma', 'Capital', 'Ciudad más poblada*', 'Población', 'Presupuesto (€)', 'Densidad (hab./km²)', 'Superficie (km²)', 'Código postal', 'Código Ministerio del Interior', 'Órgano de gobierno y administración', 'Sede (ciudad)', 'Extranjeros totales', '% de extranjeros', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'TCAC 2016-23']

,Provincia,Provincia.1_3,Posición_4,Longitud de costa (km)[2]​[3]​_4,Puesto_7,Escudo_7,Porcentaje población_7,Superficie (km²)[2]​_7,Porcentaje superficie_7,Mapa_7,Posición_8,Comunidad autónoma,Capital,Ciudad más poblada*,Población,Presupuesto (€),Densidad (hab./km²),Superficie (km²),Código postal,Código Ministerio del Interior,Órgano de gobierno y administración,Sede (ciudad),Extranjeros totales,% de extranjeros,2016,2017,2018,2019,2020,2021,2022,2023,TCAC 2016-23
0,Albacete,Ciudad Real,NaN,NaN,34,NaN,0.8 %,14 924,2.95 %,NaN,37,Castilla-La Mancha,Albacete,Albacete,NaN,NaN,2618,NaN,2,AB,Diputación de Albacete,Palacio Provincial de Albacete (Albacete),32439,74,7570409,7992903,8285269,8627212,8010434,8853382,9526877,10285196,35.86
1,Alicante,Gerona,13.0,244,4,NaN,4.14 %,5817,1.15 %,NaN,5,Comunidad Valenciana,Alicante,Alicante,NaN,NaN,34959,5816.0,3,A,Diputación de Alicante,Palacio Provincial de Alicante (Alicante),456257,218,33899084,35422930,36463569,37807882,34503374,38470028,41939432,46472807,37.09
2,Almería,Barcelona,12.0,249,21,NaN,1.57 %,8775,1.73 %,NaN,22,Andalucía,Almería,Almería,NaN,NaN,8781,8774.0,4,AL,Diputación de Almería,Edificio de la Diputación Provincial de Almerí...,168886,173,14185706,15159388,15282092,16003582,14764342,14861150,16494994,18250223,28.65
3,Araba/Álava,Vizcaya,NaN,NaN,37,NaN,0.7 %,3037,0.6 %,NaN,30,País Vasco,Vitoria,Vitoria,NaN,NaN,1126,NaN,1,VI,Diputación Foral de Álava,Palacio de la Diputación Foral de Álava (Vitoria),36831,91,11960737,12336129,12721159,12797528,11764228,11958641,12838267,14090604,17.81
4,Asturias,Soria,5.0,401,14,NaN,2.07 %,10 604,2.1 %,NaN,15,Asturias,Oviedo,Gijón,NaN,NaN,9573,NaN,33,O,No tiene[1]​,No tiene[1]​,58387,125,21675441,22538267,23185680,23666618,21376392,23617641,26690102,28350371,30.79
5,Badajoz,Lugo,NaN,NaN,25,NaN,1.35 %,21 766,4.3 %,NaN,29,Extremadura,Badajoz,Badajoz,NaN,NaN,3056,NaN,6,BA,Diputación de Badajoz,NaN,25469,66,11776505,12419839,12609609,12838980,11979224,12729424,13644123,14927003,26.75
6,Barcelona,Almería,15.0,161,2,NaN,12.13 %,7728,1.53 %,NaN,2,Cataluña,Barcelona,Barcelona,NaN,NaN,77121,7733.0,8,B,Diputación de Barcelona,Casa Serra (Barcelona),1015499,223,158516150,166618005,173436258,180560179,161885097,173917445,191251096,209563285,32.20
7,Bizkaia,Huesca,16.0,154,11,NaN,2.38 %,2217,0.44 %,NaN,6,País Vasco,Bilbao,Bilbao,NaN,NaN,52649,2217.0,48,BI,Diputación Foral de Vizcaya,Palacio de la Diputación Foral de Vizcaya (Bil...,105893,146,33686330,34314272,35599877,36737656,33016596,35910195,41009633,44229902,31.30
8,Burgos,Ávila,NaN,NaN,36,NaN,0.74 %,14 292,2.82 %,NaN,35,Castilla y León,Burgos,Burgos,NaN,NaN,2538,NaN,9,BU,Diputación de Burgos,NaN,35158,82,9572090,10054308,10494196,10628487,9620320,10224118,10709841,11303996,18.09
9,Cantabria,Burgos,8.0,284,28,NaN,1.21 %,5321,1.05 %,NaN,26,Cantabria,Santander,Santander,NaN,NaN,11156,5325.0,39,S,No tiene[4]​,No tiene[4]​,44242,98,12833899,13318023,13843935,14274351,12991241,14206538,15557155,16740663,29.93
10,Castellón,Zaragoza,18.0,139,26,NaN,1.28 %,6636,1.32%,NaN,23,Comunidad Valenciana,Castellón de la Plana,Castellón de la Plana,NaN,NaN,9421,6632.0,12,CS,Diputación de Castellón,NaN,107330,147,14223009,15506038,15685255,16135189,14341241,15775645,17355828,17661943,24.18
11,Ceuta,Jaén,23.0,26,52,NaN,0.17 %,19,0.004 %,NaN,51,Ceuta,-,-,NaN,NaN,417835,19.0,51,CE,NaN,NaN,5085,34,1537398,1553567,1611648,1659979,1535718,1634006,1766735,1862863,21.17
12,Ciudad Real,Granada,NaN,NaN,31,NaN,1.01 %,19 813,3.92 %,NaN,33,Castilla-La Mancha,Ciudad Real,Ciudad Real,NaN,NaN,2498,NaN,13,CR,Diputación de Ciudad Real,Palacio de la Diputación Provincial de Ciudad ...,36574,85,10345475,10690171,10906668,11016000,10182564,10481171,12249078,12447343,20.32
13,Cuenca,Valladolid,NaN,NaN,44,NaN,0.41 %,17 140,3.39 %,NaN,44,Castilla-La Mancha,Cuenca,Cuenca,NaN,NaN,1166,NaN,16,CU,Diputación de Cuenca,NaN,27228,69,4290139,4421111,4599762,4587758,4253677,4975017,5645595,5859753,36.59
14,Cáceres,Cádiz,NaN,NaN,35,NaN,0.79 %,19 868,3.93 %,NaN,38,Extremadura,Cáceres,Cáceres,NaN,NaN,1954,NaN,10,CC,Diputación de Cáceres,NaN,16608,49,7292966,7749707,8103645,8327152,7518119,8822093,9842522,10265612,40.76
15,Cádiz,Teruel,7.0,285,8,NaN,2.57 %,7440,1.47 %,NaN,17,Andalucía,Cádiz,Jerez de la Frontera,NaN,NaN,16955,7436.0,11,CA,Diputación de Cádiz,Palacio de la Aduana (Cádiz),62166,127,20879560,21860392,22462629,23352580,20477353,22876782,25860425,26783989,28.28
16,Córdoba,Orense,NaN,NaN,20,NaN,1.57 %,13 771,2.72 %,NaN,24,Andalucía,Córdoba,Córdoba,NaN,NaN,5614,NaN,14,CO,Diputación de Córdoba,Palacio de la Merced (Córdoba),26537,69,13567313,14113022,14292383,14237228,13134510,14512133,15518254,17217243,26.90
17,Gipuzkoa,Segovia,21.0,92,23,NaN,1.49 %,1980,0.39 %,NaN,14,País Vasco,San Sebastián,San Sebastián,NaN,NaN,37028,1909.0,20,SS,Diputación Foral de Guipúzcoa,NaN,70347,127,21467926,22934894,23594075,24464797,21891774,24644193,26370267,28427601,32.42
18,Girona,Castellón,11.0,260,19,NaN,1.69 %,5910,1.17 %,NaN,13,Cataluña,Gerona,Gerona,NaN,NaN,14051,5910.0,17,GE / GI,Diputación de Gerona,NaN,178578,175,20769493,20612222,21178933,22059649,19755932,23348038,26290879,29157484,40.39
19,Granada,Melilla,22.0,79,17,NaN,1.93 %,12 647,2.5 %,NaN,21,Andalucía,Granada,Granada,NaN,NaN,7478,NaN,18,GR,Diputación de Granada,NaN,79669,136,15888251,16314359,16798633,17538085,15967883,17357256,19181269,20836996,31.15
20,Guadalajara,Guipúzcoa,NaN,NaN,42,NaN,0.58 %,12 214,2.41 %,NaN,43,Castilla-La Mancha,Guadalajara,Guadalajara,NaN,NaN,234,NaN,19,GU,Diputación de Guadalajara,Palacio de la Diputación de Guadalajara (Guada...,43993,96,4750576,5106037,5379941,5647861,5225237,5804558,6782836,6878584,44.79
21,Huelva,Toledo,20.0,122,29,NaN,1.1 %,10 128,2 %,NaN,31,Andalucía,Huelva,Huelva,NaN,NaN,532,NaN,21,H,Diputación de Huelva,NaN,56526,124,9288980,10037865,10616525,10650577,9353422,10640222,12859210,13183665,41.93
22,Huesca,Cantabria,NaN,NaN,43,NaN,0.47 %,15 636,3.09 %,NaN,42,Aragón,Huesca,Huesca,NaN,NaN,1472,NaN,22,HU,Diputación de Huesca,NaN,33393,75,6224092,6275164,6339722,6567333,6331038,6780105,7631866,8167881,31.23
23,Islas Baleares,Málaga,1.0,1 283,9,NaN,2.54 %,4992,0.99 %,NaN,7,Islas Baleares,Palma,Palma,NaN,NaN,25037,4992.0,7,PM / IB,No tiene[3]​,No tiene[3]​,254624,182,30223284,31746251,33185968,34350576,26669106,30512146,37189162,41502526,37.32
24,Jaén,Salamanca,NaN,NaN,27,NaN,1.26 %,13 496,2.67 %,NaN,32,Andalucía,Jaén,Jaén,NaN,NaN,458,NaN,23,J,Diputación de Jaén,Palacio Provincial (Jaén),21416,61,10903626,11122181,11635259,11267290,10781405,11853935,11738138,13052058,19.70
25,La Coruña,Navarra,2.0,956,12,NaN,2.31 %,7950,1.57 %,NaN,11,Galicia,La Coruña,La Coruña,NaN,NaN,14283,7950.0,15,C,Diputación de La Coruña,NaN,60256,125,25451524,26097818,27211854,27819424,25501350,27529654,31218140,33477736,31.54
26,La Rioja,Huelva,NaN,NaN,39,NaN,0.67 %,5045,1 %,NaN,36,La Rioja,Logroño,Logroño,NaN,NaN,6478,NaN,26,LO,No tiene[5]​,No tiene[5]​,46625,106,8074094,8351707,8649852,8889997,8186915,8735750,9767469,10476650,29.76
27,Las Palmas,Guadalajara,3.0,799,10,NaN,2.38 %,4066,0.8 %,NaN,16,Canarias,Las Palmas de Gran Canaria,Las Palmas de Gran Canaria,NaN,NaN,28813,4066.0,35,GC,No tiene[6]​,No tiene[6]​,157102,155,21133454,22089679,22974312,23478690,19159502,21364107,25483866,28124631,33.08
28,León,Ceuta,NaN,NaN,33,NaN,0.91 %,15 581,3.08 %,NaN,34,Castilla y León,León,León,NaN,NaN,2875,NaN,24,LE,Diputación de León,Palacio de los Guzmanes (León),24291,63,9231953,9506147,9777598,10041788,9276493,10454424,11757261,12193704,32.08
29,Lleida,Valencia,NaN,NaN,32,NaN,0.93 %,12 172,2.41 %,NaN,28,Cataluña,Lérida,Lérida,NaN,NaN,3765,NaN,25,L,Diputación de Lérida,Palacio de la Diputación de Lérida (Lérida),91408,144,12160547,11803319,12191707,12766171,11635303,12954308,13789781,15081546,24.02
30,Lugo,Palencia,17.0,144,40,NaN,0.66 %,9856,1.95 %,NaN,40,Galicia,Lugo,Lugo,NaN,NaN,3308,9856.0,27,LU,Diputación de Lugo,NaN,21142,58,7472883,7458900,7768980,7822876,6945138,7637441,8568467,9406547,25.88
31,Madrid,Alicante,NaN,NaN,1,NaN,14.48 %,8028,1.59 %,NaN,1,Comunidad de Madrid,Madrid,Madrid,NaN,NaN,88613,NaN,28,M,No tiene[7]​,No tiene[7]​,1072173,230,214469101,224373156,233735808,243889359,221061932,239837609,267171570,295939562,37.99
32,Melilla,Sevilla,24.0,12,51,NaN,0.18 %,13,0.003 %,NaN,52,Melilla,-,-,NaN,NaN,725558,13.0,52,ML,NaN,NaN,11260,48,1452752,1466610,1510904,1560101,1452031,1534391,1655971,1753666,20.71
33,Murcia,Tarragona,10.0,274,7,NaN,3.23 %,11 314,2.24 %,NaN,9,Región de Murcia,Murcia,Murcia,NaN,NaN,14027,NaN,30,MU,No tiene[8]​,No tiene[8]​,242578,182,30009138,31192490,31715345,33000651,30440306,33603543,37380806,39838741,32.76
34,Málaga,Lérida,14.0,175,6,NaN,3.65 %,7306,1.44 %,NaN,8,Andalucía,Málaga,Málaga,NaN,NaN,24517,7308.0,29,MA,Diputación de Málaga,NaN,320766,200,28513572,29891621,31204388,32530116,28516619,32619883,37226438,41235144,44.62
35,Navarra,Cuenca,NaN,NaN,24,NaN,1.39 %,10 391,2.05 %,NaN,20,Navarra,Pamplona,Pamplona,NaN,NaN,6581,NaN,31,NaN,No tiene[9]​,No tiene[9]​,84896,136,18911331,19698794,20235995,21070268,19160726,20821017,23204474,24975376,32.07
36,Ourense,León,NaN,NaN,41,NaN,0.62 %,7273,1.44 %,NaN,41,Galicia,Orense,Orense,NaN,NaN,4197,NaN,32,OR / OU,Diputación de Orense,NaN,20924,54,6317422,6517804,6785155,7138919,6420384,7262638,8128954,8914517,41.11
37,Palencia,Badajoz,NaN,NaN,47,NaN,0.32 %,8052,1.59 %,NaN,45,Castilla y León,Palencia,Palencia,NaN,NaN,1971,NaN,34,P,Diputación de Palencia,Palacio de la Diputación de Palencia (Palencia),9356,38,4171878,4070286,4375118,4417915,4042436,4326851,4713440,5047540,20.99
38,Pontevedra,Álava,6.0,398,16,NaN,1.93 %,4495,0.89 %,NaN,19,Galicia,Pontevedra,Vigo,NaN,NaN,21086,4495.0,36,PO,Diputación de Pontevedra,Palacio de la Diputación de Pontevedra (Pontev...,47105,109,19322194,20556330,20883374,21720786,20140306,21957653,23720820,25662611,32.81
39,Salamanca,La Coruña,NaN,NaN,38,NaN,0.67 %,12 350,2.44 %,NaN,39,Castilla y León,Salamanca,Salamanca,NaN,NaN,2659,NaN,37,SA,Diputación de Salamanca,Palacio de La Salina (Salamanca),20516,54,6511439,6692406,6894146,7149679,6583497,7386843,8647606,9604292,47.50
40,Santa Cruz de Tenerife,Murcia,4.0,702,13,NaN,2.21 %,3381,0.67 %,NaN,18,Canarias,Santa Cruz de Tenerife,Santa Cruz de Tenerife,NaN,NaN,3216,3381.0,38,TF,No tiene[10]​,No tiene[10]​,161983,158,19846216,20946160,21634954,22288142,18427897,20043168,23424330,25865458,30.33
41,Segovia,Asturias,NaN,NaN,48,NaN,0.32 %,6921,1.37 %,NaN,46,Castilla y León,Segovia,Segovia,NaN,NaN,2287,NaN,40,SG,Diputación de Segovia,NaN,21309,59,3377877,3260124,3377956,3482508,3163709,3646707,4049897,4408019,30.50
42,Sevilla,La Rioja,NaN,NaN,5,NaN,4.03 %,14 036,2.77 %,NaN,4,Andalucía,Sevilla,Sevilla,NaN,NaN,1409,NaN,41,SE,Diputación de Sevilla,NaN,94994,144,36674889,38290656,39602392,40899272,37457375,41574995,45485662,48846749,33.19
43,Soria,Cáceres,NaN,NaN,50,NaN,0.18 %,10 306,2.04 %,NaN,50,Castilla y León,Soria,Soria,NaN,NaN,875,NaN,42,SO,Diputación de Soria,NaN,10936,43,2163618,2209607,2492230,2530167,2291715,2555836,2709532,2825443,30.59
44,Tarragona,Madrid,9.0,278,18,NaN,1.78 %,6303,1.25 %,NaN,12,Cataluña,Tarragona,Tarragona,NaN,NaN,13891,6303.0,43,T,Diputación de Tarragona,NaN,155717,154,23056357,24106231,24294389,24779819,21581103,24600611,27455651,29471710,27.82
45,Teruel,Pontevedra,NaN,NaN,49,NaN,0.28 %,14 810,2.93 %,NaN,48,Aragón,Teruel,Teruel,NaN,NaN,919,NaN,44,TE,Diputación de Teruel,NaN,17169,50,3256277,3222753,3381320,3422528,3120527,3529024,4072915,4324273,32.80
46,Toledo,Las Palmas,NaN,NaN,22,NaN,1.54 %,15 370,3.04 %,NaN,25,Castilla-La Mancha,Toledo,Toledo,NaN,NaN,4913,NaN,45,TO,Diputación de Toledo,Edificio de la Diputación de Toledo (Toledo),90060,137,12179643,12558737,13119285,13514472,12582448,14009858,15827632,17074065,40.19
47,Valencia,Islas Baleares,19.0,135,3,NaN,5.63 %,10 807,2.14 %,NaN,3,Comunidad Valenciana,Valencia,Valencia,NaN,NaN,2565,NaN,46,V,Diputación de Valencia,Palacio de la Baylía (Valencia),388076,208,56083303,57737744,60600750,62645457,57222556,62141233,68288134,75521155,34.66
48,Valladolid,Albacete,NaN,NaN,30,NaN,1.08 %,8110,1.6 %,NaN,27,Castilla y León,Valladolid,Valladolid,NaN,NaN,6518,NaN,47,VA,Diputación de Valladolid,Palacio de Pimentel (Valladolid),36139,84,13121197,13737381,14353734,14611199,13556027,13949687,15264558,16425196,25.18
49,Zamora,Córdoba,NaN,NaN,45,NaN,0.34 %,10 561,2.09 %,NaN,47,Castilla y León,Zamora,Zamora,NaN,NaN,1568,NaN,49,ZA,Diputación de Zamora,Hospital de la Encarnación (Zamora),8199,35,3477147,3261080,3369888,3490956,3204009,3673777,4146391,4359052,25.36
50,Zaragoza,Santa Cruz de Tenerife,NaN,NaN,15,NaN,2.03 %,17 274,3.41 %,NaN,10,Aragón,Zaragoza,Zaragoza,NaN,NaN,578,NaN,50,Z,Diputación de Zaragoza,Palacio de la Diputación Provincial (Zaragoza),146263,151,25061759,26485627,27492854,28475192,26504006,28473028,31964054,34285966,36.81
51,Ávila,Zamora,NaN,NaN,46,NaN,0.33 %,8050,1.59 %,NaN,49,Castilla y León,Ávila,Ávila,NaN,NaN,1997,NaN,5,AV,Diputación de Ávila,Torreón de los Guzmanes[2]​ (Ávila),13085,49,3003333,3087954,3191993,3296499,3056383,3247657,3468682,3726678,24.08

In [10]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv("datos_2.csv")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)


# ----------------------------
# 1. Normalizar provincias
# ----------------------------
def normalizar_provincia(x):
    if pd.isna(x):
        return x

    x = str(x).strip()

    equivalencias = {
        "Coruña, La": "La Coruña",
        "Palmas, Las": "Las Palmas",
        "Rioja, La": "La Rioja",
        "Baleares": "Islas Baleares",
        "Gerona": "Girona",
        "Lérida": "Lleida",
        "Orense": "Ourense",
        "Álava": "Araba/Álava",
        "Guipúzcoa": "Gipuzkoa",
        "Vizcaya": "Bizkaia"
    }

    return equivalencias.get(x, x)


df["Provincia"] = df["Provincia"].astype(str).str.strip().apply(normalizar_provincia)

filas_basura = ["España", "Total", "Otras (Chafarinas y Vélez de la Gomera)", "-", "nan"]
df = df[~df["Provincia"].isin(filas_basura)].copy()


# ----------------------------
# 2. Eliminar columnas basura
# ----------------------------
# elimina columnas auxiliares que no quieres analizar
columnas_a_eliminar = [
    c for c in df.columns
    if c.startswith("Unnamed")
    or c.startswith("Escudo")
    or c.startswith("Mapa")
    or c.startswith("Posición")
    or c.startswith("Puesto")
]

# elimina provincias secundarias tipo Provincia.1_3, Provincia.2_...
columnas_a_eliminar += [
    c for c in df.columns
    if c.startswith("Provincia.")   # Provincia.1_3, etc.
]

df = df.drop(columns=columnas_a_eliminar, errors="ignore")


# ----------------------------
# 3. Unificar columnas repetidas
# ----------------------------
def unificar_columnas(df, nombre_base):
    cols = [c for c in df.columns if c == nombre_base or c.startswith(nombre_base + "_")]
    if not cols:
        return df

    # primer valor no nulo por fila
    df[nombre_base] = df[cols].bfill(axis=1).iloc[:, 0]

    # borrar duplicadas con sufijo
    cols_a_borrar = [c for c in cols if c != nombre_base]
    df = df.drop(columns=cols_a_borrar, errors="ignore")

    return df


bases_a_unificar = [
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Población",
    "Presupuesto (€)",
    "Densidad (hab./km²)",
    "Superficie (km²)",
    "Código postal",
    "Código Ministerio del Interior",
    "Órgano de gobierno y administración",
    "Sede (ciudad)",
    "Extranjeros totales",
    "% de extranjeros",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Porcentaje población",
    "Porcentaje superficie",
    "Longitud de costa (km)[2]​[3]​"
]

for base in bases_a_unificar:
    df = unificar_columnas(df, base)


# ----------------------------
# 4. Consolidar filas duplicadas por provincia
# ----------------------------
def first_non_null(series):
    s = series.dropna()
    return s.iloc[0] if not s.empty else np.nan

df = df.groupby("Provincia", as_index=False).agg(first_non_null)


# ----------------------------
# 5. Limpieza numérica mejorada
# ----------------------------
def limpiar_numero(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip()

    if x in ["", "-", "—", "nan", "None"]:
        return np.nan

    # quitar referencias [1], [2], etc.
    x = re.sub(r"\[\d+\]", "", x).strip()

    # quitar espacios duros y normales
    x = x.replace("\xa0", " ")
    x = x.replace(" ", "")

    # quitar símbolo %
    x = x.replace("%", "")

    # casos:
    # 1) 1.234.567,89 -> 1234567.89
    if "," in x and "." in x:
        x = x.replace(".", "")
        x = x.replace(",", ".")
        return pd.to_numeric(x, errors="coerce")

    # 2) 7.570.409 -> entero con puntos de miles
    if x.count(".") > 1:
        x = x.replace(".", "")
        return pd.to_numeric(x, errors="coerce")

    # 3) 14 924 ya quedó como 14924 antes
    # 4) 26.18 -> decimal correcto
    # 5) 37,99 -> decimal con coma
    if "," in x:
        x = x.replace(",", ".")

    return pd.to_numeric(x, errors="coerce")


cols_numericas = [
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Presupuesto (€)",
    "Porcentaje población",
    "Densidad (hab./km²)",
    "Superficie (km²)",
    "Porcentaje superficie",
    "Extranjeros totales",
    "% de extranjeros",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23"
]

for col in cols_numericas:
    if col in df.columns:
        df[col] = df[col].apply(limpiar_numero)


# ----------------------------
# 6. Reordenar columnas útiles
# ----------------------------
columnas_preferidas = [
    "Provincia",
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Código postal",
    "Código Ministerio del Interior",
    "Superficie (km²)",
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Densidad (hab./km²)",
    "Presupuesto (€)",
    "Extranjeros totales",
    "% de extranjeros",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Órgano de gobierno y administración",
    "Sede (ciudad)"
]

columnas_finales = [c for c in columnas_preferidas if c in df.columns] + [
    c for c in df.columns if c not in columnas_preferidas
]

df = df[columnas_finales]


# ----------------------------
# 7. Guardar
# ----------------------------
df.to_csv("datos_limpios_2.csv", index=False)

print(df.head())
print("\nColumnas finales:")
print(df.columns.tolist())
print("\nShape:", df.shape)

     Provincia    Comunidad autónoma   Capital Ciudad más poblada*  \
0     Albacete    Castilla-La Mancha  Albacete            Albacete
1     Alicante  Comunidad Valenciana  Alicante            Alicante
2      Almería             Andalucía   Almería             Almería
3  Araba/Álava            País Vasco   Vitoria             Vitoria
4     Asturias              Asturias    Oviedo               Gijón

   Código postal Código Ministerio del Interior  Superficie (km²)  \
0              2                             AB               NaN
1              3                              A            5816.0
2              4                             AL            8774.0
3              1                             VI               NaN
4             33                              O           10603.0

   Longitud de costa (km)[2]​[3]​  Población  Densidad (hab./km²)  \
0                             NaN     390751                26.18
1                           244.0    2033566               349.59
2                           249.0     770554                87.81
3                             NaN     341961               112.60
4                           401.0    1015128                95.73

   Presupuesto (€)  Extranjeros totales  % de extranjeros      2016      2017  \
0      179014529.0               32.439                74   7570409   7992903
1      313871224.0              456.257               218  33899084  35422930
2      225750000.0              168.886               173  14185706  15159388
3      434606945.0               36.831                91  11960737  12336129
4      291900000.0               58.387               125  21675441  22538267

       2018      2019      2020      2021      2022      2023  TCAC 2016-23  \
0   8285269   8627212   8010434   8853382   9526877  10285196         35.86
1  36463569  37807882  34503374  38470028  41939432  46472807         37.09
2  15282092  16003582  14764342  14861150  16494994  18250223         28.65
3  12721159  12797528  11764228  11958641  12838267  14090604         17.81
4  23185680  23666618  21376392  23617641  26690102  28350371         30.79

  Órgano de gobierno y administración  \
0              Diputación de Albacete
1              Diputación de Alicante
2               Diputación de Almería
3           Diputación Foral de Álava
4                        No tiene[1]​

                                       Sede (ciudad) Superficie (km²)[2]​_7  \
0          Palacio Provincial de Albacete (Albacete)                 14 924
1          Palacio Provincial de Alicante (Alicante)                   5817
2  Edificio de la Diputación Provincial de Almerí...                   8775
3  Palacio de la Diputación Foral de Álava (Vitoria)                   3037
4                                       No tiene[1]​                 10 604

   Porcentaje población  Porcentaje superficie
0                  0.80                   2.95
1                  4.14                   1.15
2                  1.57                   1.73
3                  0.70                   0.60
4                  2.07                   2.10

Columnas finales:
['Provincia', 'Comunidad autónoma', 'Capital', 'Ciudad más poblada*', 'Código postal', 'Código Ministerio del Interior', 'Superficie (km²)', 'Longitud de costa (km)[2]\u200b[3]\u200b', 'Población', 'Densidad (hab./km²)', 'Presupuesto (€)', 'Extranjeros totales', '% de extranjeros', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'TCAC 2016-23', 'Órgano de gobierno y administración', 'Sede (ciudad)', 'Superficie (km²)[2]\u200b_7', 'Porcentaje población', 'Porcentaje superficie']

Shape: (52, 27)

In [13]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv("datos_limpios_2.csv")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)


# ----------------------------
# 1. Limpiar texto general
# ----------------------------
def limpiar_texto(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = re.sub(r"\[\d+\]", "", x)   # quita [1], [2], etc.
    x = x.replace("\xa0", " ")
    x = x.strip()
    if x in ["", "-", "—", "nan", "None"]:
        return np.nan
    return x

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].apply(limpiar_texto)


# ----------------------------
# 2. Corregir Extranjeros totales
#    Aquí el punto es separador de miles
# ----------------------------
def limpiar_entero_miles(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = x.replace(" ", "")
    x = x.replace(".", "")
    x = x.replace(",", "")
    return pd.to_numeric(x, errors="coerce")

if "Extranjeros totales" in df.columns:
    df["Extranjeros totales"] = df["Extranjeros totales"].apply(limpiar_entero_miles)


# ----------------------------
# 3. Corregir columnas porcentuales/decimales
#    Aquí NO hay que quitar puntos decimales
# ----------------------------
def limpiar_decimal_suave(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip()
    x = x.replace("%", "")
    x = x.replace("\xa0", "")
    x = x.replace(" ", "")
    x = x.replace(",", ".")
    return pd.to_numeric(x, errors="coerce")

for col in ["Densidad (hab./km²)", "% de extranjeros", "TCAC 2016-23", "Porcentaje población", "Porcentaje superficie"]:
    if col in df.columns:
        df[col] = df[col].apply(limpiar_decimal_suave)


# ----------------------------
# 4. Corregir columnas enteras que aún estén como texto
#    Pero sin tocar las que ya están bien
# ----------------------------
def convertir_si_texto_entero(col):
    if col in df.columns and df[col].dtype == "object":
        df[col] = (
            df[col]
            .astype(str)
            .str.replace("\xa0", "", regex=False)
            .str.replace(" ", "", regex=False)
            .str.replace(".", "", regex=False)
            .str.replace(",", "", regex=False)
        )
        df[col] = pd.to_numeric(df[col], errors="coerce")

for col in [
    "Población",
    "Presupuesto (€)",
    "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"
]:
    convertir_si_texto_entero(col)


# ----------------------------
# 5. Fusionar superficie auxiliar con la principal
# ----------------------------
col_aux = [c for c in df.columns if c.startswith("Superficie (km²)[2]")]
if col_aux:
    aux = col_aux[0]

    # convertir auxiliar si hace falta
    if df[aux].dtype == "object":
        df[aux] = (
            df[aux]
            .astype(str)
            .str.replace("\xa0", "", regex=False)
            .str.replace(" ", "", regex=False)
            .str.replace(".", "", regex=False)
            .str.replace(",", "", regex=False)
        )
        df[aux] = pd.to_numeric(df[aux], errors="coerce")

    # solo rellenar huecos de la principal
    if "Superficie (km²)" in df.columns:
        df["Superficie (km²)"] = df["Superficie (km²)"].fillna(df[aux])
        df = df.drop(columns=[aux])
    else:
        df = df.rename(columns={aux: "Superficie (km²)"})


# ----------------------------
# 6. Guardar versión corregida
# ----------------------------
df.to_csv("datos_final_bien.csv", index=False)

print(df.head())
print("\nShape:", df.shape)
print("\nColumnas:", df.columns.tolist())

     Provincia    Comunidad autónoma   Capital Ciudad más poblada*  \
0     Albacete    Castilla-La Mancha  Albacete            Albacete
1     Alicante  Comunidad Valenciana  Alicante            Alicante
2      Almería             Andalucía   Almería             Almería
3  Araba/Álava            País Vasco   Vitoria             Vitoria
4     Asturias              Asturias    Oviedo               Gijón

   Código postal Código Ministerio del Interior Superficie (km²)  \
0              2                             AB           14 924
1              3                              A           5816.0
2              4                             AL           8774.0
3              1                             VI             3037
4             33                              O          10603.0

   Longitud de costa (km)[2]​[3]​  Población  Densidad (hab./km²)  \
0                             NaN     390751                26.18
1                           244.0    2033566               349.59
2                           249.0     770554                87.81
3                             NaN     341961               112.60
4                           401.0    1015128                95.73

   Presupuesto (€)  Extranjeros totales  % de extranjeros      2016      2017  \
0      179014529.0                32439                74   7570409   7992903
1      313871224.0               456257               218  33899084  35422930
2      225750000.0               168886               173  14185706  15159388
3      434606945.0                36831                91  11960737  12336129
4      291900000.0                58387               125  21675441  22538267

       2018      2019      2020      2021      2022      2023  TCAC 2016-23  \
0   8285269   8627212   8010434   8853382   9526877  10285196         35.86
1  36463569  37807882  34503374  38470028  41939432  46472807         37.09
2  15282092  16003582  14764342  14861150  16494994  18250223         28.65
3  12721159  12797528  11764228  11958641  12838267  14090604         17.81
4  23185680  23666618  21376392  23617641  26690102  28350371         30.79

  Órgano de gobierno y administración  \
0              Diputación de Albacete
1              Diputación de Alicante
2               Diputación de Almería
3           Diputación Foral de Álava
4                        No tiene[1]​

                                       Sede (ciudad)  Porcentaje población  \
0          Palacio Provincial de Albacete (Albacete)                  0.80
1          Palacio Provincial de Alicante (Alicante)                  4.14
2  Edificio de la Diputación Provincial de Almerí...                  1.57
3  Palacio de la Diputación Foral de Álava (Vitoria)                  0.70
4                                       No tiene[1]​                  2.07

   Porcentaje superficie
0                   2.95
1                   1.15
2                   1.73
3                   0.60
4                   2.10

Shape: (52, 26)

Columnas: ['Provincia', 'Comunidad autónoma', 'Capital', 'Ciudad más poblada*', 'Código postal', 'Código Ministerio del Interior', 'Superficie (km²)', 'Longitud de costa (km)[2]\u200b[3]\u200b', 'Población', 'Densidad (hab./km²)', 'Presupuesto (€)', 'Extranjeros totales', '% de extranjeros', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'TCAC 2016-23', 'Órgano de gobierno y administración', 'Sede (ciudad)', 'Porcentaje población', 'Porcentaje superficie']

In [ ]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv("datos_raw.csv")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)


# ----------------------------
# 1. Normalizar provincia
# ----------------------------
def normalizar_provincia(x):
    if pd.isna(x):
        return x

    x = str(x).strip()

    equivalencias = {
        "Coruña, La": "La Coruña",
        "Palmas, Las": "Las Palmas",
        "Rioja, La": "La Rioja",
        "Baleares": "Islas Baleares",
        "Gerona": "Girona",
        "Lérida": "Lleida",
        "Orense": "Ourense",
        "Álava": "Araba/Álava",
        "Guipúzcoa": "Gipuzkoa",
        "Vizcaya": "Bizkaia"
    }

    return equivalencias.get(x, x)


df["Provincia"] = df["Provincia"].astype(str).str.strip().apply(normalizar_provincia)

filas_basura = ["España", "Total", "Otras (Chafarinas y Vélez de la Gomera)", "-", "nan"]
df = df[~df["Provincia"].isin(filas_basura)].copy()


# ----------------------------
# 2. Eliminar columnas claramente basura
# ----------------------------
cols_drop = [
    c for c in df.columns
    if c.startswith("Unnamed")
    or c.startswith("Escudo")
    or c.startswith("Mapa")
    or c.startswith("Posición")
    or c.startswith("Puesto")
    or c.startswith("Provincia.")
]

df = df.drop(columns=cols_drop, errors="ignore")


# ----------------------------
# 3. Unificar columnas equivalentes
# ----------------------------
def unificar_columnas(df, nombre_base):
    cols = [c for c in df.columns if c == nombre_base or c.startswith(nombre_base + "_")]
    if not cols:
        return df

    df[nombre_base] = df[cols].bfill(axis=1).iloc[:, 0]
    cols_a_borrar = [c for c in cols if c != nombre_base]
    df = df.drop(columns=cols_a_borrar, errors="ignore")
    return df


bases_a_unificar = [
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Población",
    "Presupuesto (€)",
    "Densidad (hab./km²)",
    "Superficie (km²)",
    "Código postal",
    "Código Ministerio del Interior",
    "Órgano de gobierno y administración",
    "Sede (ciudad)",
    "Extranjeros totales",
    "% de extranjeros",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Porcentaje población",
    "Porcentaje superficie",
    "Longitud de costa (km)[2]​[3]​"
]

for base in bases_a_unificar:
    df = unificar_columnas(df, base)


# ----------------------------
# 4. Consolidar duplicados por provincia
# ----------------------------
def first_non_null(series):
    s = series.dropna()
    return s.iloc[0] if not s.empty else np.nan

df = df.groupby("Provincia", as_index=False).agg(first_non_null)


# ----------------------------
# 5. Limpieza de texto
# ----------------------------
def limpiar_texto(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip()
    x = re.sub(r"\[\d+\]", "", x)
    x = x.replace("\xa0", " ")
    x = x.strip()

    if x in ["", "-", "—", "nan", "None"]:
        return np.nan

    return x

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].apply(limpiar_texto)


# ----------------------------
# 6. Funciones numéricas robustas
# ----------------------------
def numero_entero_es(x):
    """
    Enteros con formato español.
    Mantiene bien:
    - 32.439 -> 32439
    - 390 751 -> 390751
    - 1015499.0 -> 1015499
    """
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, np.integer)):
        return int(x)

    if isinstance(x, (float, np.floating)):
        if np.isnan(x):
            return np.nan
        return int(round(x))

    s = limpiar_texto(x)
    if pd.isna(s):
        return np.nan

    s = str(s).replace(" ", "")

    # si tiene varios puntos, son miles
    if s.count(".") > 1:
        s = s.replace(".", "")
        return pd.to_numeric(s, errors="coerce")

    # si tiene un punto y detrás hay exactamente 3 dígitos, probablemente miles
    if s.count(".") == 1 and "," not in s:
        izq, der = s.split(".")
        if der.isdigit() and len(der) == 3:
            s = izq + der
            return pd.to_numeric(s, errors="coerce")

    # si es tipo 1015499.0, convertir a int
    val = pd.to_numeric(s, errors="coerce")
    if pd.notna(val):
        return int(round(val))

    return np.nan


def numero_decimal_es(x):
    """
    Decimales con formato español.
    Mantiene bien:
    - 26.18 -> 26.18
    - 7,4 -> 7.4
    - 37,99 -> 37.99
    - 1.234,56 -> 1234.56
    """
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, np.integer, float, np.floating)):
        return float(x)

    s = limpiar_texto(x)
    if pd.isna(s):
        return np.nan

    s = str(s).replace(" ", "")

    if "," in s and "." in s:
        s = s.replace(".", "")
        s = s.replace(",", ".")
    elif "," in s:
        s = s.replace(",", ".")

    return pd.to_numeric(s, errors="coerce")


# ----------------------------
# 7. Convertir columnas por tipo
# ----------------------------
cols_enteras = [
    "Código postal",
    "Superficie (km²)",
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Presupuesto (€)",
    "Extranjeros totales",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023"
]

for col in cols_enteras:
    if col in df.columns:
        df[col] = df[col].apply(numero_entero_es)

cols_decimales = [
    "Densidad (hab./km²)",
    "% de extranjeros",
    "TCAC 2016-23",
    "Porcentaje población",
    "Porcentaje superficie"
]

for col in cols_decimales:
    if col in df.columns:
        df[col] = df[col].apply(numero_decimal_es)


# ----------------------------
# 8. Si queda una superficie auxiliar, usarla para rellenar
# ----------------------------
col_aux = [c for c in df.columns if c.startswith("Superficie (km²)[2]")]
if col_aux:
    aux = col_aux[0]
    df[aux] = df[aux].apply(numero_entero_es)

    if "Superficie (km²)" not in df.columns:
        df["Superficie (km²)"] = np.nan

    df["Superficie (km²)"] = df["Superficie (km²)"].fillna(df[aux])
    df = df.drop(columns=[aux], errors="ignore")


# ----------------------------
# 9. Reordenar columnas
# ----------------------------
columnas_finales = [
    "Provincia",
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Código postal",
    "Código Ministerio del Interior",
    "Superficie (km²)",
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Densidad (hab./km²)",
    "Presupuesto (€)",
    "Extranjeros totales",
    "% de extranjeros",
    "Porcentaje población",
    "Porcentaje superficie",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Órgano de gobierno y administración",
    "Sede (ciudad)"
]

columnas_finales = [c for c in columnas_finales if c in df.columns]
df = df[columnas_finales]


# ----------------------------
# 10. Guardar final
# ----------------------------
df.to_csv("datos_finales.csv", index=False)

print(df.head())
print("\nShape:", df.shape)
print("\nColumnas:", df.columns.tolist())

     Provincia      Comunidad autónoma   Capital Ciudad más poblada*  \
0     Albacete      Castilla-La Mancha  Albacete            Albacete
1     Alicante    Comunidad Valenciana  Alicante            Alicante
2      Almería               Andalucía   Almería             Almería
3  Araba/Álava              País Vasco   Vitoria             Vitoria
4     Asturias  Principado de Asturias    Oviedo               Gijón

   Código postal Código Ministerio del Interior  Superficie (km²)  \
0              2                             AB           14924.0
1              3                              A            5816.0
2              4                             AL            8774.0
3              1                             VI            3037.0
4             33                              O           10603.0

   Longitud de costa (km)[2]​[3]​  Población  Densidad (hab./km²)  \
0                             NaN     390751                26.18
1                           244.0    2033566               349.59
2                           249.0     770554                87.81
3                             NaN     341961               112.60
4                           401.0    1015128                95.73

   Presupuesto (€)  Extranjeros totales  % de extranjeros  \
0      179014529.0                32439              74.0
1      313871224.0               456257             218.0
2      225750000.0               168886             173.0
3      434606945.0                36831              91.0
4      291900000.0                58387             125.0

   Porcentaje población  Porcentaje superficie      2016      2017      2018  \
0                   NaN                    NaN   7570409   7992903   8285269
1                   NaN                    NaN  33899084  35422930  36463569
2                   NaN                    NaN  14185706  15159388  15282092
3                   NaN                    NaN  11960737  12336129  12721159
4                   NaN                    NaN  21675441  22538267  23185680

       2019      2020      2021      2022      2023  TCAC 2016-23  \
0   8627212   8010434   8853382   9526877  10285196           NaN
1  37807882  34503374  38470028  41939432  46472807           NaN
2  16003582  14764342  14861150  16494994  18250223           NaN
3  12797528  11764228  11958641  12838267  14090604           NaN
4  23666618  21376392  23617641  26690102  28350371           NaN

  Órgano de gobierno y administración  \
0              Diputación de Albacete
1              Diputación de Alicante
2               Diputación de Almería
3           Diputación Foral de Álava
4                        No tiene[1]​

                                       Sede (ciudad)
0          Palacio Provincial de Albacete (Albacete)
1          Palacio Provincial de Alicante (Alicante)
2  Edificio de la Diputación Provincial de Almerí...
3  Palacio de la Diputación Foral de Álava (Vitoria)
4                                       No tiene[1]​

Shape: (52, 26)

Columnas: ['Provincia', 'Comunidad autónoma', 'Capital', 'Ciudad más poblada*', 'Código postal', 'Código Ministerio del Interior', 'Superficie (km²)', 'Longitud de costa (km)[2]\u200b[3]\u200b', 'Población', 'Densidad (hab./km²)', 'Presupuesto (€)', 'Extranjeros totales', '% de extranjeros', 'Porcentaje población', 'Porcentaje superficie', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'TCAC 2016-23', 'Órgano de gobierno y administración', 'Sede (ciudad)']

In [15]:
print(df[["Porcentaje población", "Porcentaje superficie"]].head())

   Porcentaje población  Porcentaje superficie
0                   NaN                    NaN
1                   NaN                    NaN
2                   NaN                    NaN
3                   NaN                    NaN
4                   NaN                    NaN

In [17]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv("datos_raw.csv")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)


# ----------------------------
# 0. Normalizar nombres de columnas
# ----------------------------
def limpiar_nombre_columna(c):
    c = str(c)
    c = c.replace("\u200b", "")   # zero-width space
    c = c.replace("\xa0", " ")    # non-breaking space
    c = re.sub(r"\s+", " ", c)
    return c.strip()

df.columns = [limpiar_nombre_columna(c) for c in df.columns]


# ----------------------------
# 1. Normalizar provincia
# ----------------------------
def normalizar_provincia(x):
    if pd.isna(x):
        return x

    x = str(x).strip()

    equivalencias = {
        "Coruña, La": "La Coruña",
        "Palmas, Las": "Las Palmas",
        "Rioja, La": "La Rioja",
        "Baleares": "Islas Baleares",
        "Gerona": "Girona",
        "Lérida": "Lleida",
        "Orense": "Ourense",
        "Álava": "Araba/Álava",
        "Guipúzcoa": "Gipuzkoa",
        "Vizcaya": "Bizkaia"
    }

    return equivalencias.get(x, x)


df["Provincia"] = df["Provincia"].astype(str).str.strip().apply(normalizar_provincia)

filas_basura = ["España", "Total", "Otras (Chafarinas y Vélez de la Gomera)", "-", "nan"]
df = df[~df["Provincia"].isin(filas_basura)].copy()


# ----------------------------
# 2. Eliminar columnas claramente basura
# ----------------------------
cols_drop = [
    c for c in df.columns
    if c.startswith("Unnamed")
    or c.startswith("Escudo")
    or c.startswith("Mapa")
    or c.startswith("Posición")
    or c.startswith("Puesto")
    or c.startswith("Provincia.")
]

df = df.drop(columns=cols_drop, errors="ignore")


# ----------------------------
# 3. Unificar columnas equivalentes
# ----------------------------
def unificar_columnas(df, nombre_base):
    cols = [c for c in df.columns if c == nombre_base or c.startswith(nombre_base + "_")]
    if not cols:
        return df

    df[nombre_base] = df[cols].bfill(axis=1).iloc[:, 0]
    cols_a_borrar = [c for c in cols if c != nombre_base]
    df = df.drop(columns=cols_a_borrar, errors="ignore")
    return df


bases_a_unificar = [
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Población",
    "Presupuesto (€)",
    "Densidad (hab./km²)",
    "Superficie (km²)",
    "Código postal",
    "Código Ministerio del Interior",
    "Órgano de gobierno y administración",
    "Sede (ciudad)",
    "Extranjeros totales",
    "% de extranjeros",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Porcentaje población",
    "Porcentaje superficie",
    "Longitud de costa (km)[2]​[3]​",
    "Superficie (km²)[2]​"
]

for base in bases_a_unificar:
    df = unificar_columnas(df, base)

# refuerzo extra para porcentajes, por si venían con sufijos raros
for base in ["Porcentaje población", "Porcentaje superficie"]:
    cols = [c for c in df.columns if c == base or c.startswith(base + "_")]
    if cols:
        df[base] = df[cols].bfill(axis=1).iloc[:, 0]


# ----------------------------
# 4. Consolidar duplicados por provincia
# ----------------------------
def first_non_null(series):
    s = series.dropna()
    return s.iloc[0] if not s.empty else np.nan

df = df.groupby("Provincia", as_index=False).agg(first_non_null)


# ----------------------------
# 5. Limpieza de texto
# ----------------------------
def limpiar_texto(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip()
    x = re.sub(r"\[\d+\]", "", x)
    x = x.replace("\xa0", " ")
    x = x.replace("\u200b", "")
    x = x.strip()

    if x in ["", "-", "—", "nan", "None"]:
        return np.nan

    return x

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].apply(limpiar_texto)


# ----------------------------
# 6. Funciones numéricas robustas
# ----------------------------
def numero_entero_es(x):
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, np.integer)):
        return int(x)

    if isinstance(x, (float, np.floating)):
        if np.isnan(x):
            return np.nan
        return int(round(x))

    s = limpiar_texto(x)
    if pd.isna(s):
        return np.nan

    s = str(s).replace(" ", "")

    # varios puntos -> miles
    if s.count(".") > 1:
        s = s.replace(".", "")
        return pd.to_numeric(s, errors="coerce")

    # un punto y 3 dígitos detrás -> miles
    if s.count(".") == 1 and "," not in s:
        izq, der = s.split(".")
        if der.isdigit() and len(der) == 3:
            s = izq + der
            return pd.to_numeric(s, errors="coerce")

    val = pd.to_numeric(s, errors="coerce")
    if pd.notna(val):
        return int(round(val))

    return np.nan


def numero_decimal_es(x):
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, np.integer, float, np.floating)):
        return float(x)

    s = limpiar_texto(x)
    if pd.isna(s):
        return np.nan

    s = str(s).replace(" ", "")

    if "," in s and "." in s:
        s = s.replace(".", "")
        s = s.replace(",", ".")
    elif "," in s:
        s = s.replace(",", ".")

    return pd.to_numeric(s, errors="coerce")


def porcentaje_extranjeros_corregido(x):
    """
    Corrige casos como:
    74  -> 7.4
    218 -> 21.8
    230 -> 23.0
    """
    val = numero_decimal_es(x)
    if pd.isna(val):
        return np.nan

    if 100 < val < 1000:
        return val / 10

    return val


# ----------------------------
# 7. Convertir columnas por tipo
# ----------------------------
cols_enteras = [
    "Código postal",
    "Superficie (km²)",
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Presupuesto (€)",
    "Extranjeros totales",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023"
]

for col in cols_enteras:
    if col in df.columns:
        df[col] = df[col].apply(numero_entero_es)

cols_decimales = [
    "Densidad (hab./km²)",
    "TCAC 2016-23",
    "Porcentaje población",
    "Porcentaje superficie"
]

for col in cols_decimales:
    if col in df.columns:
        df[col] = df[col].apply(numero_decimal_es)

if "% de extranjeros" in df.columns:
    df["% de extranjeros"] = df["% de extranjeros"].apply(porcentaje_extranjeros_corregido)


# ----------------------------
# 8. Si queda una superficie auxiliar, usarla para rellenar
# ----------------------------
col_aux = [c for c in df.columns if c.startswith("Superficie (km²)[2]")]
if col_aux:
    aux = col_aux[0]
    df[aux] = df[aux].apply(numero_entero_es)

    if "Superficie (km²)" not in df.columns:
        df["Superficie (km²)"] = np.nan

    df["Superficie (km²)"] = df["Superficie (km²)"].fillna(df[aux])
    df = df.drop(columns=[aux], errors="ignore")


# ----------------------------
# 9. Normalizar comunidades autónomas
# ----------------------------
def normalizar_ccaa(x):
    if pd.isna(x):
        return x

    x = str(x).strip()

    mapa = {
        "Principado de Asturias": "Asturias",
        "Comunidad Foral de Navarra": "Navarra"
    }

    return mapa.get(x, x)

if "Comunidad autónoma" in df.columns:
    df["Comunidad autónoma"] = df["Comunidad autónoma"].apply(normalizar_ccaa)


# ----------------------------
# 10. Reordenar columnas
# ----------------------------
columnas_finales = [
    "Provincia",
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Código postal",
    "Código Ministerio del Interior",
    "Superficie (km²)",
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Densidad (hab./km²)",
    "Presupuesto (€)",
    "Extranjeros totales",
    "% de extranjeros",
    "Porcentaje población",
    "Porcentaje superficie",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Órgano de gobierno y administración",
    "Sede (ciudad)"
]

columnas_finales = [c for c in columnas_finales if c in df.columns]
df = df[columnas_finales]


# ----------------------------
# 11. Guardar final
# ----------------------------
df.to_csv("datos_finales.csv", index=False)

print(df.head())
print("\nShape:", df.shape)
print("\nColumnas:", df.columns.tolist())
print("\nComprobación porcentajes:")
if "% de extranjeros" in df.columns:
    print(df[["Provincia", "% de extranjeros"]].head(10))
if "Porcentaje población" in df.columns and "Porcentaje superficie" in df.columns:
    print(df[["Provincia", "Porcentaje población", "Porcentaje superficie"]].head(10))

     Provincia    Comunidad autónoma   Capital Ciudad más poblada*  \
0     Albacete    Castilla-La Mancha  Albacete            Albacete
1     Alicante  Comunidad Valenciana  Alicante            Alicante
2      Almería             Andalucía   Almería             Almería
3  Araba/Álava            País Vasco   Vitoria             Vitoria
4     Asturias              Asturias    Oviedo               Gijón

   Código postal Código Ministerio del Interior  Superficie (km²)  Población  \
0              2                             AB           14924.0     390751
1              3                              A            5816.0    2033566
2              4                             AL            8774.0     770554
3              1                             VI            3037.0     341961
4             33                              O           10603.0    1015128

   Densidad (hab./km²)  Presupuesto (€)  Extranjeros totales  \
0                26.18      179014529.0                32439
1               349.59      313871224.0               456257
2                87.81      225750000.0               168886
3               112.60      434606945.0                36831
4                95.73      291900000.0                58387

   % de extranjeros  Porcentaje población  Porcentaje superficie      2016  \
0              74.0                   NaN                    NaN   7570409
1              21.8                   NaN                    NaN  33899084
2              17.3                   NaN                    NaN  14185706
3              91.0                   NaN                    NaN  11960737
4              12.5                   NaN                    NaN  21675441

       2017      2018      2019      2020      2021      2022      2023  \
0   7992903   8285269   8627212   8010434   8853382   9526877  10285196
1  35422930  36463569  37807882  34503374  38470028  41939432  46472807
2  15159388  15282092  16003582  14764342  14861150  16494994  18250223
3  12336129  12721159  12797528  11764228  11958641  12838267  14090604
4  22538267  23185680  23666618  21376392  23617641  26690102  28350371

   TCAC 2016-23 Órgano de gobierno y administración  \
0           NaN              Diputación de Albacete
1           NaN              Diputación de Alicante
2           NaN               Diputación de Almería
3           NaN           Diputación Foral de Álava
4           NaN                        No tiene[1]​

                                       Sede (ciudad)
0          Palacio Provincial de Albacete (Albacete)
1          Palacio Provincial de Alicante (Alicante)
2  Edificio de la Diputación Provincial de Almerí...
3  Palacio de la Diputación Foral de Álava (Vitoria)
4                                       No tiene[1]​

Shape: (52, 25)

Columnas: ['Provincia', 'Comunidad autónoma', 'Capital', 'Ciudad más poblada*', 'Código postal', 'Código Ministerio del Interior', 'Superficie (km²)', 'Población', 'Densidad (hab./km²)', 'Presupuesto (€)', 'Extranjeros totales', '% de extranjeros', 'Porcentaje población', 'Porcentaje superficie', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'TCAC 2016-23', 'Órgano de gobierno y administración', 'Sede (ciudad)']

Comprobación porcentajes:
     Provincia  % de extranjeros
0     Albacete              74.0
1     Alicante              21.8
2      Almería              17.3
3  Araba/Álava              91.0
4     Asturias              12.5
5      Badajoz              66.0
6    Barcelona              22.3
7      Bizkaia              14.6
8       Burgos              82.0
9    Cantabria              98.0
     Provincia  Porcentaje población  Porcentaje superficie
0     Albacete                   NaN                    NaN
1     Alicante                   NaN                    NaN
2      Almería                   NaN                    NaN
3  Araba/Álava                   NaN                    NaN
4     Asturias                   NaN                    NaN
5      Badajoz                   NaN                    NaN
6    Barcelona                   NaN                    NaN
7      Bizkaia                   NaN                    NaN
8       Burgos                   NaN                    NaN
9    Cantabria                   NaN                    NaN

# Este es el que funciona bien

In [18]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv("datos_raw.csv")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)


# ----------------------------
# 0. Normalizar nombres de columnas
# ----------------------------
def limpiar_nombre_columna(c):
    c = str(c)
    c = c.replace("\u200b", "")
    c = c.replace("\xa0", " ")
    c = re.sub(r"\s+", " ", c)
    return c.strip()

df.columns = [limpiar_nombre_columna(c) for c in df.columns]


# ----------------------------
# 1. Normalizar provincia
# ----------------------------
def normalizar_provincia(x):
    if pd.isna(x):
        return x

    x = str(x).strip()

    equivalencias = {
        "Coruña, La": "La Coruña",
        "Palmas, Las": "Las Palmas",
        "Rioja, La": "La Rioja",
        "Baleares": "Islas Baleares",
        "Gerona": "Girona",
        "Lérida": "Lleida",
        "Orense": "Ourense",
        "Álava": "Araba/Álava",
        "Guipúzcoa": "Gipuzkoa",
        "Vizcaya": "Bizkaia"
    }

    return equivalencias.get(x, x)

df["Provincia"] = df["Provincia"].astype(str).str.strip().apply(normalizar_provincia)

filas_basura = ["España", "Total", "Otras (Chafarinas y Vélez de la Gomera)", "-", "nan"]
df = df[~df["Provincia"].isin(filas_basura)].copy()


# ----------------------------
# 2. Eliminar columnas basura
# ----------------------------
cols_drop = [
    c for c in df.columns
    if c.startswith("Unnamed")
    or c.startswith("Escudo")
    or c.startswith("Mapa")
    or c.startswith("Posición")
    or c.startswith("Puesto")
    or c.startswith("Provincia.")
]

df = df.drop(columns=cols_drop, errors="ignore")


# ----------------------------
# 3. Unificar columnas equivalentes
# ----------------------------
def unificar_columnas(df, nombre_base):
    cols = [c for c in df.columns if c == nombre_base or c.startswith(nombre_base + "_")]
    if not cols:
        return df

    df[nombre_base] = df[cols].bfill(axis=1).iloc[:, 0]
    cols_a_borrar = [c for c in cols if c != nombre_base]
    df = df.drop(columns=cols_a_borrar, errors="ignore")
    return df


bases_a_unificar = [
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Población",
    "Presupuesto (€)",
    "Densidad (hab./km²)",
    "Superficie (km²)",
    "Código postal",
    "Código Ministerio del Interior",
    "Órgano de gobierno y administración",
    "Sede (ciudad)",
    "Extranjeros totales",
    "% de extranjeros",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Porcentaje población",
    "Porcentaje superficie",
    "Longitud de costa (km)[2]​[3]​",
    "Superficie (km²)[2]​"
]

for base in bases_a_unificar:
    df = unificar_columnas(df, base)


# ----------------------------
# 4. Consolidar duplicados por provincia
# ----------------------------
def first_non_null(series):
    s = series.dropna()
    return s.iloc[0] if not s.empty else np.nan

df = df.groupby("Provincia", as_index=False).agg(first_non_null)


# ----------------------------
# 5. Limpieza de texto
# ----------------------------
def limpiar_texto(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip()
    x = re.sub(r"\[\d+\]", "", x)
    x = x.replace("\xa0", " ")
    x = x.replace("\u200b", "")
    x = x.strip()

    if x in ["", "-", "—", "nan", "None"]:
        return np.nan

    return x

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].apply(limpiar_texto)


# ----------------------------
# 6. Funciones numéricas
# ----------------------------
def numero_entero_es(x):
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, np.integer)):
        return int(x)

    if isinstance(x, (float, np.floating)):
        if np.isnan(x):
            return np.nan
        return int(round(x))

    s = limpiar_texto(x)
    if pd.isna(s):
        return np.nan

    s = str(s).replace(" ", "")
    s = s.replace("%", "")

    if s.count(".") > 1:
        s = s.replace(".", "")
        return pd.to_numeric(s, errors="coerce")

    if s.count(".") == 1 and "," not in s:
        izq, der = s.split(".")
        if der.isdigit() and len(der) == 3:
            s = izq + der
            return pd.to_numeric(s, errors="coerce")

    val = pd.to_numeric(s, errors="coerce")
    if pd.notna(val):
        return int(round(val))

    return np.nan


def numero_decimal_es(x):
    if pd.isna(x):
        return np.nan

    if isinstance(x, (int, np.integer, float, np.floating)):
        return float(x)

    s = limpiar_texto(x)
    if pd.isna(s):
        return np.nan

    s = str(s).replace(" ", "")
    s = s.replace("%", "")

    if "," in s and "." in s:
        s = s.replace(".", "")
        s = s.replace(",", ".")
    elif "," in s:
        s = s.replace(",", ".")

    return pd.to_numeric(s, errors="coerce")


def porcentaje_extranjeros_corregido(x):
    """
    En esta tabla concreta el scraper deja:
    74 -> 7.4
    218 -> 21.8
    230 -> 23.0
    """
    val = numero_decimal_es(x)
    if pd.isna(val):
        return np.nan
    return val / 10


# ----------------------------
# 7. Convertir columnas por tipo
# ----------------------------
cols_enteras = [
    "Código postal",
    "Superficie (km²)",
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Presupuesto (€)",
    "Extranjeros totales",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023"
]

for col in cols_enteras:
    if col in df.columns:
        df[col] = df[col].apply(numero_entero_es)

cols_decimales = [
    "Densidad (hab./km²)",
    "TCAC 2016-23",
    "Porcentaje población",
    "Porcentaje superficie"
]

for col in cols_decimales:
    if col in df.columns:
        df[col] = df[col].apply(numero_decimal_es)

if "% de extranjeros" in df.columns:
    df["% de extranjeros"] = df["% de extranjeros"].apply(porcentaje_extranjeros_corregido)


# ----------------------------
# 8. Rellenar superficie auxiliar
# ----------------------------
col_aux = [c for c in df.columns if c.startswith("Superficie (km²)[2]")]
if col_aux:
    aux = col_aux[0]
    df[aux] = df[aux].apply(numero_entero_es)

    if "Superficie (km²)" not in df.columns:
        df["Superficie (km²)"] = np.nan

    df["Superficie (km²)"] = df["Superficie (km²)"].fillna(df[aux])
    df = df.drop(columns=[aux], errors="ignore")


# ----------------------------
# 9. Normalizar comunidades autónomas
# ----------------------------
def normalizar_ccaa(x):
    if pd.isna(x):
        return x

    x = str(x).strip()

    mapa = {
        "Principado de Asturias": "Asturias",
        "Comunidad Foral de Navarra": "Navarra"
    }

    return mapa.get(x, x)

if "Comunidad autónoma" in df.columns:
    df["Comunidad autónoma"] = df["Comunidad autónoma"].apply(normalizar_ccaa)


# ----------------------------
# 10. Reordenar columnas
# ----------------------------
columnas_finales = [
    "Provincia",
    "Comunidad autónoma",
    "Capital",
    "Ciudad más poblada*",
    "Código postal",
    "Código Ministerio del Interior",
    "Superficie (km²)",
    "Longitud de costa (km)[2]​[3]​",
    "Población",
    "Densidad (hab./km²)",
    "Presupuesto (€)",
    "Extranjeros totales",
    "% de extranjeros",
    "Porcentaje población",
    "Porcentaje superficie",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "TCAC 2016-23",
    "Órgano de gobierno y administración",
    "Sede (ciudad)"
]

columnas_finales = [c for c in columnas_finales if c in df.columns]
df = df[columnas_finales]


# ----------------------------
# 11. Guardar
# ----------------------------
df.to_csv("datos_finales.csv", index=False)

print(df.head())
print("\nShape:", df.shape)
print("\nColumnas:", df.columns.tolist())
print("\nComprobación:")
print(df[["Provincia", "% de extranjeros", "Porcentaje población", "Porcentaje superficie"]].head(10))

     Provincia    Comunidad autónoma   Capital Ciudad más poblada*  \
0     Albacete    Castilla-La Mancha  Albacete            Albacete
1     Alicante  Comunidad Valenciana  Alicante            Alicante
2      Almería             Andalucía   Almería             Almería
3  Araba/Álava            País Vasco   Vitoria             Vitoria
4     Asturias              Asturias    Oviedo               Gijón

   Código postal Código Ministerio del Interior  Superficie (km²)  Población  \
0              2                             AB           14924.0     390751
1              3                              A            5816.0    2033566
2              4                             AL            8774.0     770554
3              1                             VI            3037.0     341961
4             33                              O           10603.0    1015128

   Densidad (hab./km²)  Presupuesto (€)  Extranjeros totales  \
0                26.18      179014529.0                32439
1               349.59      313871224.0               456257
2                87.81      225750000.0               168886
3               112.60      434606945.0                36831
4                95.73      291900000.0                58387

   % de extranjeros  Porcentaje población  Porcentaje superficie      2016  \
0               7.4                  0.80                   2.95   7570409
1              21.8                  4.14                   1.15  33899084
2              17.3                  1.57                   1.73  14185706
3               9.1                  0.70                   0.60  11960737
4              12.5                  2.07                   2.10  21675441

       2017      2018      2019      2020      2021      2022      2023  \
0   7992903   8285269   8627212   8010434   8853382   9526877  10285196
1  35422930  36463569  37807882  34503374  38470028  41939432  46472807
2  15159388  15282092  16003582  14764342  14861150  16494994  18250223
3  12336129  12721159  12797528  11764228  11958641  12838267  14090604
4  22538267  23185680  23666618  21376392  23617641  26690102  28350371

   TCAC 2016-23 Órgano de gobierno y administración  \
0         35.86              Diputación de Albacete
1         37.09              Diputación de Alicante
2         28.65               Diputación de Almería
3         17.81           Diputación Foral de Álava
4         30.79                        No tiene[1]​

                                       Sede (ciudad)
0          Palacio Provincial de Albacete (Albacete)
1          Palacio Provincial de Alicante (Alicante)
2  Edificio de la Diputación Provincial de Almerí...
3  Palacio de la Diputación Foral de Álava (Vitoria)
4                                       No tiene[1]​

Shape: (52, 25)

Columnas: ['Provincia', 'Comunidad autónoma', 'Capital', 'Ciudad más poblada*', 'Código postal', 'Código Ministerio del Interior', 'Superficie (km²)', 'Población', 'Densidad (hab./km²)', 'Presupuesto (€)', 'Extranjeros totales', '% de extranjeros', 'Porcentaje población', 'Porcentaje superficie', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'TCAC 2016-23', 'Órgano de gobierno y administración', 'Sede (ciudad)']

Comprobación:
     Provincia  % de extranjeros  Porcentaje población  Porcentaje superficie
0     Albacete               7.4                  0.80                   2.95
1     Alicante              21.8                  4.14                   1.15
2      Almería              17.3                  1.57                   1.73
3  Araba/Álava               9.1                  0.70                   0.60
4     Asturias              12.5                  2.07                   2.10
5      Badajoz               6.6                  1.35                   4.30
6    Barcelona              22.3                 12.13                   1.53
7      Bizkaia              14.6                  2.38                   0.44
8       Burgos               8.2                  0.74                   2.82
9    Cantabria               9.8                  1.21                   1.05